"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { demoOperator, games, money, type LedgerEvent } from "../../../lib/platform";

export default function OperatorSimulator(){
 const [balance,setBalance]=useState(1000); const [events,setEvents]=useState<LedgerEvent[]>([]); const [status,setStatus]=useState("Ready for sandbox request"); const [sessionId]=useState(()=>`ses_${Math.random().toString(16).slice(2,8)}`);
 const emit=(type:LedgerEvent["type"],amount=0)=>{const next=balance+amount;if(next<0){setStatus("Rejected · insufficient sandbox balance");return}setBalance(next);setEvents(e=>[{id:`evt_${Math.random().toString(16).slice(2,8)}`,sessionId,type,amount,balanceAfter:next,createdAt:new Date().toISOString()},...e]);setStatus(`${type.toUpperCase()} accepted · ${money(next)} available`)};
 const payload=useMemo(()=>({operator_id:demoOperator.id,session_id:sessionId,game_id:games[0].id,player_id:"player_demo_001",environment:"sandbox"}),[sessionId]);
 return <main className="min-h-screen bg-[#080808] text-[#f4f1e9]"><div className="mx-auto max-w-6xl px-5 py-8 md:px-8"><header className="flex justify-between border-b border-zinc-900 pb-6"><div><Link href="/" className="text-xs font-black uppercase tracking-[.24em]">Small Game Lab.</Link><p className="mt-2 text-[9px] font-black uppercase tracking-[.25em] text-orange-500">Integration Simulator</p></div><Link href="/dashboard/platform" className="text-[10px] font-black uppercase tracking-[.16em] text-zinc-500">Control room →</Link></header><section className="py-10"><p className="text-[10px] font-black uppercase tracking-[.3em] text-zinc-600">Sandbox only</p><h1 className="mt-2 text-5xl font-black tracking-[-.05em]">Run the integration.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-zinc-500">Authenticate a player, place a sandbox bet, settle a win or roll it back. Nothing here touches real-money systems.</p></section><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="border border-zinc-900 p-6"><p className="text-[9px] font-black uppercase tracking-[.2em] text-zinc-600">Demo wallet</p><p className="mt-3 text-5xl font-black">{money(balance)}</p><p className="mt-3 text-xs text-zinc-600">{status}</p><div className="mt-8 grid grid-cols-2 gap-2"><button onClick={()=>emit("authenticate")} className="border border-zinc-800 px-4 py-3 text-[9px] font-black uppercase">Authenticate</button><button onClick={()=>emit("bet",-20)} className="border border-zinc-800 px-4 py-3 text-[9px] font-black uppercase">Bet £20</button><button onClick={()=>emit("win",24)} className="border border-orange-700 bg-orange-600 px-4 py-3 text-[9px] font-black uppercase text-black">Win £24</button><button onClick={()=>emit("rollback",20)} className="border border-zinc-800 px-4 py-3 text-[9px] font-black uppercase">Rollback £20</button></div></section><section className="border border-zinc-900"><div className="border-b border-zinc-900 px-5 py-4"><h2 className="text-xs font-black uppercase tracking-[.18em]">Request / session</h2></div><pre className="overflow-auto p-5 text-xs leading-6 text-zinc-400">{JSON.stringify(payload,null,2)}</pre><div className="border-t border-zinc-900 px-5 py-4"><p className="text-[9px] font-black uppercase tracking-[.2em] text-zinc-600">Event ledger</p>{events.length===0?<p className="mt-4 text-xs text-zinc-700">No events yet. Run the flow above.</p>:events.map(e=><div key={e.id} className="mt-3 flex justify-between border-b border-zinc-900 pb-3 text-xs"><span className="font-black uppercase">{e.type}</span><span className="text-zinc-500">{e.amount>0?"+":""}{money(e.amount)} → {money(e.balanceAfter)}</span></div>)}</div></section></div></div></main>;
}
