"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Enemy={id:number;x:number;y:number;hp:number;maxHp:number;speed:number;kind:"grunt"|"runner"|"brute"};
type Shot={id:number;x:number;y:number;vx:number;vy:number};

const W=1000,H=560;

export default function LastStandGameV5(){
 const [running,setRunning]=useState(false),[hp,setHp]=useState(100),[ammo,setAmmo]=useState(12),[wave,setWave]=useState(1),[kills,setKills]=useState(0),[cash,setCash]=useState(120),[enemies,setEnemies]=useState<Enemy[]>([]),[shots,setShots]=useState<Shot[]>([]),[aim,setAim]=useState(0),[playerX,setPlayerX]=useState(190),[shake,setShake]=useState(0),[muzzle,setMuzzle]=useState(false),[hit,setHit]=useState(false),[dead,setDead]=useState(false);
 const ids=useRef(1),keys=useRef(new Set<string>()),last=useRef(0);
 const spawn=(n:number)=>setEnemies(Array.from({length:Math.min(7+n*2,20)},(_,i)=>{const r=Math.random();const kind=r>.9&&n>3?"brute":r>.76?"runner":"grunt";const max=kind==="brute"?4+Math.floor(n/2):kind==="runner"?2:1;return{id:ids.current++,x:W+60+i*55+Math.random()*180,y:410,hp:max,maxHp:max,speed:(kind==="runner"?1.35:kind==="brute"?.42:.7)+n*.025,kind}}));
 const start=()=>{setRunning(true);setDead(false);setHp(100);setAmmo(12);setWave(1);setKills(0);setCash(120);setPlayerX(190);spawn(1)};
 const fire=()=>{if(!running||ammo<=0)return;const angle=aim*.9-.45;setAmmo(a=>a-1);setShots(s=>[...s,{id:ids.current++,x:playerX+40,y:397,vx:Math.cos(angle)*18,vy:-Math.sin(angle)*18}]);setMuzzle(true);setShake(2);window.setTimeout(()=>setMuzzle(false),70)};
 useEffect(()=>{const d=(e:KeyboardEvent)=>{keys.current.add(e.key.toLowerCase());if(e.code==="Space"){e.preventDefault();fire()}if(e.key.toLowerCase()==="r")setAmmo(12)};const u=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener("keydown",d);addEventListener("keyup",u);return()=>{removeEventListener("keydown",d);removeEventListener("keyup",u)}},[running,ammo,aim,playerX]);
 useEffect(()=>{if(!running)return;const t=setInterval(()=>{setPlayerX(x=>Math.max(120,Math.min(300,x+(keys.current.has("a")||keys.current.has("arrowleft")?-4:keys.current.has("d")||keys.current.has("arrowright")?4:0))))},30);return()=>clearInterval(t)},[running]);
 useEffect(()=>{if(!running)return;const t=setInterval(()=>{setShots(s=>s.map(b=>({...b,x:b.x+b.vx,y:b.y+b.vy})).filter(b=>b.x<W+50&&b.y>0));setEnemies(es=>es.map(e=>({...e,x:e.x-e.speed})).filter(e=>{if(e.x<playerX+35){setHp(v=>Math.max(0,v-(e.kind==="brute"?16:e.kind==="runner"?9:5)));setHit(true);setShake(5);window.setTimeout(()=>setHit(false),100);return false}return true}))},35);return()=>clearInterval(t)},[running,playerX]);
 useEffect(()=>{if(!running||!shots.length)return;setShots(cur=>{const next=cur.filter(b=>{const i=enemies.findIndex(e=>Math.hypot(e.x-b.x,e.y-b.y)<28);if(i<0)return true;setEnemies(es=>es.map((e,j)=>j===i?{...e,hp:e.hp-1}:e).filter(e=>e.hp>0));setCash(c=>c+12);setKills(k=>k+1);setHit(true);setShake(4);return false});return next})},[shots,enemies,running]);
 useEffect(()=>{if(hp<=0&&running){setRunning(false);setDead(true);setEnemies([]);setShots([])}} ,[hp,running]);
 useEffect(()=>{if(!running||enemies.length||last.current===0)return;setWave(w=>w+1);setCash(c=>c+50);spawn(wave+1);},[enemies.length,running,wave]);
 const pointer=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect();setAim(Math.max(-.5,Math.min(.5,(e.clientX-r.left)/r.width-.5)));if(e.pointerType!=="mouse")fire()};
 const stars=useMemo(()=>Array.from({length:45},(_,i)=>({left:(i*73)%100,top:(i*37)%52,size:i%5===0?2:1})),[]);
 return <div className="overflow-hidden rounded-sm border border-[#333] bg-[#07090b] shadow-[0_30px_80px_rgba(0,0,0,.55)]"><div className="flex items-center justify-between border-b border-[#30343a] bg-[#111418] px-4 py-3 text-[10px] font-black uppercase tracking-[.2em]"><span className="text-[#d7d2c7]">LAST STAND <span className="text-[#f06422]">/ 001</span></span><span className="text-[#f06422]">WAVE {String(wave).padStart(2,"0")}</span></div><div onPointerMove={e=>pointer(e)} onPointerDown={pointer} className="relative aspect-[16/9] min-h-[380px] overflow-hidden" style={{transform:`translate(${(Math.random()-.5)*shake}px,${(Math.random()-.5)*shake}px)`,background:"linear-gradient(#17212b 0%,#26313b 48%,#171b1e 49%,#0b0d0f 100%)"}}>{stars.map(s=><i key={s.left+s.top} className="absolute rounded-full bg-[#d9e4e8] opacity-40" style={{left:`${s.left}%`,top:`${s.top}%`,width:s.size,height:s.size}}/>)}<div className="absolute inset-x-0 top-[48%] h-1 bg-[#59616a]"/><div className="absolute bottom-0 inset-x-0 h-[51%] bg-[repeating-linear-gradient(90deg,#111417_0_8px,#15191d_8px_16px)]"/><div className="absolute bottom-[22%] left-[7%] h-28 w-20 border-4 border-[#59616a] bg-[#1a1e22] shadow-[12px_10px_0_#0a0c0e]"/><div className="absolute bottom-[22%] left-[39%] h-20 w-28 border-2 border-[#343a40] bg-[#121518]"/><div className="absolute bottom-[22%] left-[72%] h-36 w-16 border-4 border-[#424950] bg-[#15191c]"/>
 <div className="absolute bottom-[21%]" style={{left:`${playerX/W*100}%`}}><div className="relative h-20 w-12"><div className="absolute left-3 top-1 h-7 w-7 rounded-full border-2 border-[#d6b08a] bg-[#765238]"/><div className="absolute left-1 top-7 h-10 w-10 rounded-sm border-2 border-[#0b0d0f] bg-[#28342f]"/><div className="absolute left-0 top-9 h-3 w-9 rotate-[-18deg] rounded bg-[#59665c]"/><div className="absolute left-7 top-8 h-2 w-16 origin-left rotate-[-18deg] rounded bg-[#17191b] border border-[#70777a]"/>{muzzle&&<b className="absolute left-20 top-1 h-4 w-10 rounded-full bg-[#ffd66b] blur-sm"/>}</div></div>
 {enemies.map(e=><div key={e.id} className="absolute bottom-[21%]" style={{left:`${e.x/W*100}%`}}><div className={`${e.kind==="brute"?"h-16 w-14 bg-[#5b2220] border-2 border-[#a43a2f]":"h-11 w-8 bg-[#333b3e] border-2 border-[#687276]"} relative rounded-sm shadow-[5px_5px_0_rgba(0,0,0,.4)]`}><div className="absolute left-1 top-2 h-2 w-2 rounded-full bg-[#f06422] shadow-[8px_0_0_#f06422]"/><div className="absolute -top-3 left-0 h-1.5 w-full bg-[#17191b]"><div className="h-full bg-[#f06422]" style={{width:`${e.hp/e.maxHp*100}%`}}/></div></div></div>)}
 {shots.map(b=><div key={b.id} className="absolute h-1 w-8 rounded-full bg-[#ffe7a8] shadow-[0_0_10px_#f5a623]" style={{left:`${b.x/W*100}%`,top:`${b.y/H*100}%`,transform:`rotate(${Math.atan2(b.vy,b.vx)}rad)`}}/>)}{hit&&<div className="pointer-events-none absolute inset-0 bg-[#f06422]/10"/>}<div className="absolute left-4 top-4 flex flex-wrap gap-3 text-[9px] font-black uppercase tracking-[.16em] text-[#d7d2c7]"><span className="border border-[#3b4147] bg-[#101316]/90 px-2 py-1">HP {hp}</span><span className="border border-[#3b4147] bg-[#101316]/90 px-2 py-1">AMMO {ammo}/12</span><span className="border border-[#3b4147] bg-[#101316]/90 px-2 py-1">${cash}</span><span className="border border-[#3b4147] bg-[#101316]/90 px-2 py-1">KILLS {kills}</span></div>{!running&&<div className="absolute inset-0 flex items-center justify-center bg-[#050607]/55 backdrop-blur-[2px]"><div className="text-center"><p className="text-[9px] font-black uppercase tracking-[.35em] text-[#f06422]">Small Game Lab · Field Test</p><h2 className="mt-3 text-5xl font-black uppercase tracking-[-.04em] text-[#e9e4da]">{dead?"Line lost.":"Hold the line."}</h2><p className="mt-3 text-xs uppercase tracking-[.16em] text-[#92989d]">A/D move · mouse aim · space fire</p><button onClick={start} className="mt-7 border border-[#f06422] bg-[#f06422] px-8 py-4 text-[10px] font-black uppercase tracking-[.2em] text-[#08090a]">{dead?"Deploy again":"Start field test"}</button></div></div>}</div><div className="flex items-center justify-between border-t border-[#30343a] bg-[#101316] px-4 py-3 text-[9px] font-black uppercase tracking-[.16em] text-[#777f85]"><span>FIELD TEST BUILD</span><span>SPACE / TAP · FIRE</span><button onClick={()=>setAmmo(12)} className="border border-[#3b4147] px-3 py-2 text-[#b5bbc0]">Reload</button></div></div>}
