"use client";

import { useEffect, useRef, useState } from "react";

type Phase = "menu" | "playing" | "upgrade" | "gameover" | "victory";
type Kind = "grunt" | "runner" | "brute" | "boss";
type Enemy = { id:number;x:number;y:number;hp:number;max:number;speed:number;kind:Kind };
type Bullet = { id:number;x:number;y:number;vx:number;vy:number;damage:number;life:number };

const WIDTH=1200, HEIGHT=675, GROUND=520;
const prices={damage:90,mag:110,medic:130,troop:180};

export default function LastStandComplete(){
 const canvas=useRef<HTMLCanvasElement>(null);
 const state=useRef({phase:"menu" as Phase,wave:1,hp:100,ammo:12,mag:12,cash:120,kills:0,score:0,damage:1,medic:0,troops:0,player:170,enemies:[] as Enemy[],bullets:[] as Bullet,next:1,boss:false,muted:false,best:0,highWave:0});
 const keys=useRef(new Set<string>()),mouse=useRef({x:850,y:350,down:false}),audio=useRef<AudioContext|null>(null);
 const [hud,setHud]=useState({phase:"menu" as Phase,wave:1,hp:100,ammo:12,mag:12,cash:120,kills:0,score:0,boss:false,best:0});
 const save=()=>{try{localStorage.setItem("sgl-last-stand",JSON.stringify({best:state.current.best,highestWave:state.current.highWave}));}catch{}};
 const sound=(f:number,d=.05)=>{if(state.current.muted)return;try{audio.current??=new AudioContext();const o=audio.current.createOscillator(),g=audio.current.createGain();o.frequency.value=f;o.type="square";g.gain.setValueAtTime(.025,audio.current.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.current.currentTime+d);o.connect(g);g.connect(audio.current.destination);o.start();o.stop(audio.current.currentTime+d);}catch{}};
 const sync=()=>{const s=state.current;setHud({phase:s.phase,wave:s.wave,hp:Math.max(0,Math.ceil(s.hp)),ammo:s.ammo,mag:s.mag,cash:s.cash,kills:s.kills,score:s.score,boss:s.boss,best:s.best});};
 const spawn=()=>{const s=state.current;s.enemies=[];s.boss=s.wave%5===0;const count=s.boss?5:Math.min(8+Math.floor(s.wave*1.5),22);for(let i=0;i<count;i++){const r=Math.random(),kind:Kind=s.boss&&i===count-1?"boss":s.wave>2&&r>.88?"brute":r>.72?"runner":"grunt";const max=kind==="boss"?120+s.wave*10:kind==="brute"?7+Math.floor(s.wave/2):kind==="runner"?2:1;s.enemies.push({id:s.next++,x:WIDTH+80+i*65+Math.random()*240,y:GROUND-50,hp:max,max,speed:kind==="boss"?.16:kind==="brute"?.34:kind==="runner"?1.2:.62,kind});}};
 const start=()=>{const s=state.current;s.phase="playing";s.wave=1;s.hp=100;s.ammo=s.mag=12;s.cash=120;s.kills=0;s.score=0;s.damage=1;s.medic=0;s.troops=0;s.player=170;s.enemies=[];s.bullets=[];spawn();sync();sound(220,.12);};
 const fire=()=>{const s=state.current;if(s.phase!=="playing"||s.ammo<1)return;const dx=mouse.current.x-(s.player+25),dy=mouse.current.y-(GROUND-65),len=Math.hypot(dx,dy)||1;s.bullets.push({id:s.next++,x:s.player+40,y:GROUND-65,vx:dx/len*17,vy:dy/len*17,damage:s.damage,life:1});s.ammo--;sound(140,.035);sync();};
 const upgrade=(type:keyof typeof prices)=>{const s=state.current;if(s.cash<prices[type])return;s.cash-=prices[type];if(type==="damage")s.damage++;if(type==="mag")s.mag+=4;if(type==="medic")s.medic+=1;if(type==="troop")s.troops++;s.phase="playing";s.wave++;spawn();sound(type==="damage"?650:420,.08);sync();};
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem("sgl-last-stand")||"{}");state.current.best=x.best||0;state.current.highWave=x.highestWave||0;}catch{};sync();},[]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;const resize=()=>{const d=Math.min(2,devicePixelRatio||1);c.width=WIDTH*d;c.height=HEIGHT*d;ctx.setTransform(d,0,0,d,0,0);};resize();addEventListener("resize",resize);
 const point=(e:PointerEvent)=>{const r=c.getBoundingClientRect();mouse.current.x=(e.clientX-r.left)/r.width*WIDTH;mouse.current.y=(e.clientY-r.top)/r.height*HEIGHT;};const down=(e:PointerEvent)=>{point(e);mouse.current.down=true;fire();};const up=()=>mouse.current.down=false;c.addEventListener("pointermove",point);c.addEventListener("pointerdown",down);addEventListener("pointerup",up);
 const kd=(e:KeyboardEvent)=>{keys.current.add(e.key.toLowerCase());if(e.code==="Space"){e.preventDefault();fire();}if(e.key.toLowerCase()==="r"){state.current.ammo=state.current.mag;sound(280,.07);sync();}if(e.key.toLowerCase()==="m")state.current.muted=!state.current.muted;};const ku=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener("keydown",kd);addEventListener("keyup",ku);
 let raf=0,last=performance.now();const loop=(now:number)=>{const dt=Math.min(.035,(now-last)/1000);last=now;const s=state.current;
  if(s.phase==="playing"){
   const dir=(keys.current.has("a")||keys.current.has("arrowleft")?-1:0)+(keys.current.has("d")||keys.current.has("arrowright")?1:0);s.player=Math.max(80,Math.min(340,s.player+dir*210*dt));if(mouse.current.down)fire();
   s.hp=Math.min(100,s.hp+s.medic*.18*dt);
   for(const e of s.enemies){e.x-=e.speed*60*dt;if(e.x<s.player+45){s.hp-= (e.kind==="boss"?20:e.kind==="brute"?11:e.kind==="runner"?8:5)*dt;e.x=s.player+45;}}
   for(const b of s.bullets){b.x+=b.vx*60*dt;b.y+=b.vy*60*dt;b.life-=dt;const hit=s.enemies.find(e=>Math.hypot(e.x+15-b.x,e.y-b.y)<34);if(hit){hit.hp-=b.damage;b.life=0;s.cash+=10;s.score+=25;}}
   s.bullets=s.bullets.filter(b=>b.life>0&&b.x<WIDTH+40&&b.x>-40);
   const dead=s.enemies.filter(e=>e.hp<=0);if(dead.length){dead.forEach(e=>{s.kills++;s.score+=e.kind==="boss"?3000:e.kind==="brute"?120:e.kind==="runner"?70:40;if(e.kind==="boss"){s.cash+=1000;s.phase="victory";sound(880,.25);}});s.enemies=s.enemies.filter(e=>e.hp>0);}
   if(s.hp<=0)s.phase="gameover";else if(s.enemies.length===0)s.phase="upgrade";
   if(s.phase==="gameover"||s.phase==="victory"){s.best=Math.max(s.best,s.score);s.highWave=Math.max(s.highWave,s.wave);save();}
  }
  draw(ctx);sync();raf=requestAnimationFrame(loop);};
 const draw=(g:CanvasRenderingContext2D)=>{const s=state.current;g.clearRect(0,0,WIDTH,HEIGHT);const sky=g.createLinearGradient(0,0,0,GROUND);sky.addColorStop(0,"#101a23");sky.addColorStop(.65,"#2d3b42");sky.addColorStop(1,"#53514a");g.fillStyle=sky;g.fillRect(0,0,WIDTH,GROUND);g.fillStyle="#0d1012";g.fillRect(0,GROUND,WIDTH,HEIGHT-GROUND);
  for(let i=0;i<15;i++){g.fillStyle=i%2?"#2a3437":"#354044";g.fillRect(i*90,GROUND-90-(i%3)*20,45,90+(i%3)*20);}g.fillStyle="#202728";g.fillRect(0,GROUND-12,WIDTH,12);g.strokeStyle="#404948";for(let x=0;x<WIDTH;x+=55){g.beginPath();g.moveTo(x,GROUND);g.lineTo(x+35,HEIGHT);g.stroke();}
  g.fillStyle="#394541";g.fillRect(70,GROUND-115,120,103);g.fillStyle="#1a2021";g.fillRect(90,GROUND-88,34,32);g.fillRect(150,GROUND-88,34,32);g.fillStyle="#515c57";g.fillRect(470,GROUND-72,125,60);g.fillStyle="#171c1d";g.fillRect(490,GROUND-50,85,38);
  const px=s.player,py=GROUND-72;g.fillStyle="#c08c66";g.beginPath();g.arc(px+20,py+10,12,0,Math.PI*2);g.fill();g.fillStyle="#26332d";g.fillRect(px+8,py+21,25,34);g.fillStyle="#0d1112";g.fillRect(px+5,py+53,10,18);g.fillRect(px+27,py+53,10,18);const a=Math.atan2(mouse.current.y-(py+28),mouse.current.x-(px+20));g.save();g.translate(px+22,py+30);g.rotate(a);g.fillStyle="#0b0d0e";g.fillRect(0,-4,60,8);g.fillStyle="#707975";g.fillRect(22,-3,24,6);g.restore();
  for(let i=0;i<s.troops;i++){const tx=px-35-i*28;g.fillStyle="#65756a";g.fillRect(tx,GROUND-55,20,28);g.fillStyle="#b98763";g.beginPath();g.arc(tx+10,GROUND-58,7,0,Math.PI*2);g.fill();}
  for(const e of s.enemies){const boss=e.kind==="boss",w=boss?60:e.kind==="brute"?42:28,h=boss?72:e.kind==="brute"?62:48;g.fillStyle=boss?"#87362f":e.kind==="brute"?"#572e2b":e.kind==="runner"?"#68716f":"#4d5957";g.fillRect(e.x,e.y-h,w,h);g.fillStyle="#f06422";g.fillRect(e.x+6,e.y-h+12,7,7);g.fillRect(e.x+w-13,e.y-h+12,7,7);g.fillStyle="#17191a";g.fillRect(e.x,e.y-h-10,w,5);g.fillStyle="#f06422";g.fillRect(e.x,e.y-h-10,w*(e.hp/e.max),5);if(boss){g.strokeStyle="#f06422";g.lineWidth=2;g.strokeRect(e.x-4,e.y-h-18,w+8,h+22);}}
  for(const b of s.bullets){g.strokeStyle="#ffe9ad";g.lineWidth=3;g.beginPath();g.moveTo(b.x,b.y);g.lineTo(b.x-b.vx*.7,b.y-b.vy*.7);g.stroke();}
  const v=g.createRadialGradient(WIDTH/2,HEIGHT/2,160,WIDTH/2,HEIGHT/2,680);v.addColorStop(0,"rgba(0,0,0,0)");v.addColorStop(1,"rgba(0,0,0,.65)");g.fillStyle=v;g.fillRect(0,0,WIDTH,HEIGHT);
 };raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);removeEventListener("resize",resize);c.removeEventListener("pointermove",point);c.removeEventListener("pointerdown",down);removeEventListener("pointerup",up);removeEventListener("keydown",kd);removeEventListener("keyup",ku);};},[]);
 const p=hud.phase;
 return <div className="overflow-hidden rounded-sm border border-zinc-800 bg-[#080a0b] shadow-2xl"><div className="relative"><canvas ref={canvas} className="block w-full touch-none cursor-crosshair"/><div className="pointer-events-none absolute inset-x-0 top-0 flex justify-between p-4 text-[9px] font-black uppercase tracking-[.16em]"><div className="flex gap-2"><span className="bg-black/75 px-3 py-2">HP {hud.hp}</span><span className="bg-black/75 px-3 py-2">AMMO {hud.ammo}/{hud.mag}</span><span className="bg-black/75 px-3 py-2 text-orange-400">${hud.cash}</span></div><span className="bg-black/75 px-3 py-2">WAVE {String(hud.wave).padStart(2,"0")} · {hud.score.toLocaleString()}</span></div>
 {p==="playing"&&hud.boss&&<div className="pointer-events-none absolute left-1/2 top-20 -translate-x-1/2 bg-black/80 px-6 py-2 text-[10px] font-black uppercase tracking-[.3em] text-orange-400">BOSS WAVE</div>}
 {p!=="playing"&&<div className="absolute inset-0 flex items-center justify-center bg-black/65 p-5 backdrop-blur-[3px]"><div className="w-full max-w-2xl text-center">
 {p==="menu"&&<><p className="text-[10px] font-black uppercase tracking-[.4em] text-orange-500">Small Game Lab · Game 001</p><h2 className="mt-3 text-5xl font-black uppercase tracking-[-.05em] text-[#f2eee5] md:text-7xl">Hold the line.</h2><p className="mx-auto mt-4 max-w-lg text-sm leading-6 text-zinc-400">A tiny old-school action game rebuilt for the modern web. Move. Aim. Shoot. Upgrade. Survive.</p><button onClick={start} className="pointer-events-auto mt-7 bg-orange-500 px-9 py-4 text-[10px] font-black uppercase tracking-[.22em] text-black">Deploy</button><p className="mt-4 text-[9px] uppercase tracking-[.18em] text-zinc-600">A/D move · click or space fire · R reload · M mute</p></>}
 {p==="upgrade"&&<><p className="text-[10px] font-black uppercase tracking-[.35em] text-orange-500">Wave clear</p><h2 className="mt-2 text-4xl font-black uppercase">Choose your edge.</h2><p className="mt-2 text-xs uppercase tracking-[.15em] text-zinc-500">${hud.cash} available · next wave {hud.wave+1}</p><div className="pointer-events-auto mt-7 grid gap-3 sm:grid-cols-2">{([['damage','Heavy rounds','+1 damage · $90'],['mag','Extended mag','+4 magazine · $110'],['medic','Field medic','regeneration · $130'],['troop','Rifleman','automatic support · $180']] as const).map(([key,title,desc])=><button key={key} onClick={()=>upgrade(key)} className="border border-zinc-700 bg-zinc-950 p-5 text-left hover:border-orange-500"><b className="block text-sm uppercase">{title}</b><span className="mt-1 block text-xs text-zinc-500">{desc}</span></button>)}</div></>}
 {(p==="gameover"||p==="victory")&&<><p className="text-[10px] font-black uppercase tracking-[.35em] text-orange-500">{p==="victory"?"Sector secured":"Position lost"}</p><h2 className="mt-2 text-5xl font-black uppercase">{p==="victory"?"You held the line.":"Line lost."}</h2><div className="mx-auto mt-6 grid max-w-md grid-cols-3 gap-px bg-zinc-800"><div className="bg-black/80 p-4"><b className="block text-xl">{hud.wave}</b><span className="text-[9px] uppercase text-zinc-500">Wave</span></div><div className="bg-black/80 p-4"><b className="block text-xl">{hud.kills}</b><span className="text-[9px] uppercase text-zinc-500">Kills</span></div><div className="bg-black/80 p-4"><b className="block text-xl">{hud.score.toLocaleString()}</b><span className="text-[9px] uppercase text-zinc-500">Score</span></div></div><button onClick={start} className="pointer-events-auto mt-7 bg-orange-500 px-9 py-4 text-[10px] font-black uppercase tracking-[.22em] text-black">Deploy again</button></>}
 </div></div>}</div><div className="flex justify-between border-t border-zinc-800 bg-[#101214] px-4 py-3 text-[9px] font-black uppercase tracking-[.16em] text-zinc-600"><span>FIELD TEST · BUILD 0.5</span><span className="hidden sm:block">A/D · CLICK/SPACE · R · M</span><span>{hud.kills} KILLS</span></div></div>;
}
