"use client";

import { useEffect, useRef, useState } from "react";

type Enemy={id:number;x:number;y:number;hp:number;maxHp:number;kind:"grunt"|"runner"|"brute"};
type Shot={id:number;x:number;y:number;vx:number;vy:number};

const W=1000,H=560;

export default function LastStandPolished(){
 const [started,setStarted]=useState(false),[hp,setHp]=useState(100),[ammo,setAmmo]=useState(12),[cash,setCash]=useState(120),[wave,setWave]=useState(1),[kills,setKills]=useState(0),[enemies,setEnemies]=useState<Enemy[]>([]),[shots,setShots]=useState<Shot[]>([]),[aim,setAim]=useState(0),[x,setX]=useState(180),[damage,setDamage]=useState(1),[upgrade,setUpgrade]=useState(false),[boss,setBoss]=useState(false);
 const keys=useRef(new Set<string>()); const id=useRef(1);
 const spawn=(w:number)=>{const isBoss=w%5===0;setBoss(isBoss);const n=isBoss?1:Math.min(4+w*2,18);setEnemies(Array.from({length:n},(_,i)=>{const kind=isBoss?"brute":(i%7===0&&w>2?"brute":i%5===0?"runner":"grunt");const max=isBoss?40:kind==="brute"?5:kind==="runner"?2:1;return{id:id.current++,x:W+80+i*55,y:410,hp:max,maxHp:max,kind}}));};
 const start=()=>{setStarted(true);setHp(100);setAmmo(12);setCash(120);setWave(1);setKills(0);setDamage(1);setUpgrade(false);setShots([]);setX(180);spawn(1)};
 const fire=()=>{if(!started||upgrade||ammo<1)return;const a=aim;setAmmo(v=>v-1);setShots(s=>[...s,{id:id.current++,x:x+35,y:410,vx:24,vy:a}]);};
 useEffect(()=>{const d=(e:KeyboardEvent)=>{keys.current.add(e.key.toLowerCase());if(e.code==="Space"){e.preventDefault();fire()}if(e.key.toLowerCase()==="r")setAmmo(12)};const u=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener("keydown",d);addEventListener("keyup",u);return()=>{removeEventListener("keydown",d);removeEventListener("keyup",u)}},[started,upgrade,ammo,aim,x]);
 useEffect(()=>{if(!started||upgrade)return;const t=setInterval(()=>setX(v=>Math.max(120,Math.min(260,v+(keys.current.has("a")||keys.current.has("arrowleft")?-4:keys.current.has("d")||keys.current.has("arrowright")?4:0)))),30);return()=>clearInterval(t)},[started,upgrade]);
 useEffect(()=>{if(!started||upgrade)return;const t=setInterval(()=>{setShots(s=>s.map(b=>({...b,x:b.x+b.vx,y:b.y+b.vy})).filter(b=>b.x<W));setEnemies(es=>es.map(e=>({...e,x:e.x-(e.kind==="runner"?1.7:e.kind==="brute"?.55:.9)})).filter(e=>{if(e.x<270){setHp(v=>Math.max(0,v-(e.kind==="brute"?15:6)));return false}return true}))},40);return()=>clearInterval(t)},[started,upgrade]);
 useEffect(()=>{if(!started||upgrade)return;setShots(s=>{let changed=false;const next=s.filter(b=>{const i=enemies.findIndex(e=>Math.hypot(e.x-b.x,e.y-410)<32);if(i<0)return true;changed=true;setEnemies(es=>es.map((e,j)=>j===i?{...e,hp:e.hp-damage}:e).filter(e=>e.hp>0));setCash(v=>v+10);setKills(v=>v+1);return false});return changed?next:s})},[shots,enemies,started,upgrade,damage]);
 useEffect(()=>{if(!started||enemies.length)return;setUpgrade(true)},[started,enemies.length]);
 const next=(type:string)=>{if(type==="damage")setDamage(v=>v+1);if(type==="ammo")setAmmo(18);if(type==="medic")setHp(v=>Math.min(100,v+25));setWave(v=>v+1);setCash(v=>v+50);setUpgrade(false);setTimeout(()=>spawn(wave+1),50)};
 const pointer=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect();setAim(((e.clientX-r.left)/r.width-.5)*7);if(e.pointerType!=="mouse")fire()};
 return <div className="overflow-hidden rounded border border-zinc-800 bg-[#070707] shadow-[0_30px_100px_rgba(0,0,0,.55)]"><div className="flex justify-between border-b border-zinc-800 bg-[#111] px-4 py-3 text-[10px] font-black uppercase tracking-[.2em]"><span>LAST STAND <b className="text-orange-500">/ 001</b></span><span className="text-orange-500">WAVE {String(wave).padStart(2,"0")}</span></div><div onPointerMove={e=>e.pointerType==="mouse"&&pointer(e)} onPointerDown={pointer} className="relative aspect-video overflow-hidden bg-[radial-gradient(circle_at_65%_20%,#39424b_0,#182028_30%,#090c0f_68%)]">
 <div className="absolute inset-x-0 top-[55%] h-px bg-zinc-500/40"/><div className="absolute inset-x-0 bottom-0 h-[45%] bg-[linear-gradient(180deg,#151a1e,#080a0c)]"/><div className="absolute bottom-[18%] left-[8%] h-28 w-24 border-4 border-zinc-700 bg-zinc-900 shadow-[18px_12px_0_#050607]"/><div className="absolute bottom-[18%] left-[45%] h-16 w-36 border-2 border-zinc-700 bg-zinc-900"/><div className="absolute bottom-[18%] right-[8%] h-36 w-20 border-4 border-zinc-700 bg-zinc-900"/>
 <div className="absolute bottom-[18%]" style={{left:`${x/10}%`}}><div className="relative h-20 w-12"><div className="absolute left-3 top-0 h-7 w-7 rounded-full border-2 border-[#b88762] bg-[#60442f]"/><div className="absolute left-1 top-7 h-11 w-10 rounded bg-[#26342d] border-2 border-zinc-900"/><div className="absolute left-7 top-8 h-2 w-16 origin-left -rotate-12 rounded bg-[#1a1c1d] border border-zinc-600"/></div></div>
 {enemies.map(e=><div key={e.id} className="absolute bottom-[18%]" style={{left:`${e.x/10}%`}}><div className={`${boss?"h-24 w-24 bg-red-900 border-4 border-red-500":""} ${!boss&&e.kind==="brute"?"h-14 w-12 bg-red-800 border-2 border-red-400":""} ${!boss&&e.kind==="runner"?"h-9 w-6 bg-red-500":""} ${!boss&&e.kind==="grunt"?"h-11 w-8 bg-zinc-500":""} relative rounded-sm`}><div className="absolute -top-3 left-0 h-1.5 w-full bg-black"><div className="h-full bg-orange-500" style={{width:`${e.hp/e.maxHp*100}%`}}/></div>{boss&&<div className="absolute inset-0 grid place-items-center text-[8px] font-black text-white">BOSS</div>}</div></div>)}
 {shots.map(b=><span key={b.id} className="absolute h-1.5 w-9 rounded-full bg-yellow-200 shadow-[0_0_14px_#f59e0b]" style={{left:`${b.x/10}%`,top:`${b.y/H*100}%`,transform:`rotate(${Math.atan2(b.vy,b.vx)}rad)`}}/>)}
 <div className="absolute left-4 top-4 flex flex-wrap gap-2 text-[9px] font-black uppercase tracking-widest text-white"><span className="bg-black/70 px-2 py-1">HP {hp}</span><span className="bg-black/70 px-2 py-1">AMMO {ammo}/12</span><span className="bg-black/70 px-2 py-1">${cash}</span><span className="bg-black/70 px-2 py-1">KILLS {kills}</span></div>
 {boss&&<div className="absolute left-1/2 top-14 w-1/2 -translate-x-1/2"><div className="text-center text-[9px] font-black uppercase tracking-[.3em] text-red-400">Heavy contact</div></div>}
 {!started&&<div className="absolute inset-0 grid place-items-center bg-black/60 backdrop-blur-sm"><div className="text-center"><p className="text-[9px] font-black uppercase tracking-[.35em] text-orange-500">Small Game Lab · Field Test</p><h2 className="mt-3 text-5xl font-black uppercase text-white">Hold the line.</h2><button onClick={start} className="mt-6 bg-orange-500 px-8 py-4 text-[10px] font-black uppercase tracking-[.2em] text-black">Deploy</button></div></div>}
 {upgrade&&started&&<div className="absolute inset-0 grid place-items-center bg-black/75 backdrop-blur-sm"><div className="w-full max-w-2xl p-5 text-center"><p className="text-[9px] font-black uppercase tracking-[.3em] text-orange-500">Wave cleared</p><h2 className="mt-2 text-3xl font-black uppercase text-white">Choose your edge</h2><div className="mt-6 grid gap-3 md:grid-cols-3">{[["damage","Hotter rounds","+1 damage"],["ammo","Bigger mag","+6 ammo"],["medic","Field medic","+25 HP"]].map(([a,b,c])=><button key={a} onClick={()=>next(a)} className="border border-zinc-700 bg-zinc-950 p-5 text-left hover:border-orange-500"><b className="block text-sm font-black uppercase text-white">{b}</b><span className="mt-2 block text-xs text-zinc-500">{c}</span></button>)}</div></div></div>}
 </div><div className="flex justify-between border-t border-zinc-800 bg-[#111] px-4 py-3 text-[9px] font-black uppercase tracking-[.16em] text-zinc-500"><span>A/D move · mouse aim · space fire · R reload</span><button onClick={()=>setAmmo(12)} className="border border-zinc-700 px-3 py-1 text-zinc-300">Reload</button></div></div>;
}
