"use client";

import { useEffect, useState } from "react";

type Enemy={id:number,x:number,y:number,hp:number};

export default function OneMoreRoom(){
 const [running,setRunning]=useState(false),[hp,setHp]=useState(100),[ammo,setAmmo]=useState(8),[room,setRoom]=useState(1),[score,setScore]=useState(0),[enemies,setEnemies]=useState<Enemy[]>([]),[upgrade,setUpgrade]=useState(false);
 const spawn=(r:number)=>setEnemies(Array.from({length:Math.min(2+r,7)},(_,i)=>({id:Date.now()+i,x:18+Math.random()*64,y:18+Math.random()*54,hp:r>3?2:1})));
 const start=()=>{setRunning(true);setHp(100);setAmmo(8);setRoom(1);setScore(0);setUpgrade(false);spawn(1)};
 useEffect(()=>{if(!running||upgrade)return;const t=window.setInterval(()=>{setEnemies(es=>es.map(e=>({...e,x:e.x+(Math.random()-.5)*2,y:e.y+(Math.random()-.5)*2})));if(Math.random()<.16)setHp(v=>Math.max(0,v-2))},500);return()=>clearInterval(t)},[running,upgrade]);
 const fire=(x:number,y:number)=>{if(!running||upgrade||ammo<1)return;setAmmo(v=>v-1);setEnemies(es=>{let hit=false;const next=es.map(e=>{if(!hit&&Math.hypot(e.x-x,e.y-y)<15){hit=true;return {...e,hp:e.hp-1}}return e}).filter(e=>e.hp>0);if(hit)setScore(v=>v+10);return next})};
 useEffect(()=>{if(running&&hp<=0){setRunning(false)}},[hp,running]);
 useEffect(()=>{if(running&&!upgrade&&enemies.length===0){setUpgrade(true)}},[enemies.length,running,upgrade]);
 const choose=(kind:string)=>{if(kind==="damage")setScore(v=>v+25);if(kind==="medic")setHp(v=>Math.min(100,v+25));if(kind==="ammo")setAmmo(v=>v+4);setRoom(v=>v+1);setUpgrade(false);setTimeout(()=>spawn(room+1),250)};
 return <div className="overflow-hidden border border-zinc-800 bg-[#08090b]"><div className="flex justify-between border-b border-zinc-800 px-4 py-3 text-[10px] font-black uppercase tracking-[.2em]"><span>THE LONG RUN · 02</span><span className="text-[#d94b2b]">ROOM {String(room).padStart(2,"0")}</span></div><div className="relative aspect-video overflow-hidden bg-[#17181a]"><div className="absolute inset-[8%] border-8 border-[#30343a] bg-[#0d0f12] shadow-[inset_0_0_80px_rgba(0,0,0,.8)]"/><div className="absolute left-[12%] top-[12%] h-5 w-28 bg-[#d94b2b]/60"/><div className="absolute right-[12%] top-[12%] h-5 w-20 bg-zinc-700"/><div className="absolute bottom-[12%] left-[45%] h-24 w-10 bg-[#d94b2b] shadow-[8px_8px_0_#17191b]"/><div className="absolute bottom-[28%] left-[46%] h-7 w-7 rounded-full bg-[#b77b5a]"/>{enemies.map(e=><button key={e.id} onClick={()=>fire(e.x,e.y)} className="absolute h-10 w-8 -translate-x-1/2 -translate-y-1/2 bg-zinc-600 shadow-[0_0_0_2px_#17191b]" style={{left:`${e.x}%`,top:`${e.y}%`}}><span className="absolute -top-2 left-0 h-1 w-full bg-zinc-900"><span className="block h-full bg-[#d94b2b]" style={{width:`${e.hp*100}%`}}/></span></button>)}<div className="absolute left-4 top-4 flex gap-2 text-[9px] font-black uppercase tracking-widest"><span className="bg-black/70 px-2 py-1">HP {hp}</span><span className="bg-black/70 px-2 py-1">AMMO {ammo}</span><span className="bg-black/70 px-2 py-1">SCORE {score}</span></div>{upgrade&&<div className="absolute inset-0 grid place-items-center bg-black/75"><div className="w-full max-w-xl p-5 text-center"><p className="text-[9px] font-black uppercase tracking-[.3em] text-[#d94b2b]">Room cleared</p><h2 className="mt-2 text-3xl font-black uppercase">Choose your edge</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["damage","Hotter rounds"],["medic","Field medic"],["ammo","Extra magazines"]].map(([k,t])=><button key={k} onClick={()=>choose(k)} className="border border-zinc-700 p-4 text-left hover:border-[#d94b2b]"><b className="text-xs uppercase">{t}</b></button>)}</div></div></div>}{!running&&<div className="absolute inset-0 grid place-items-center bg-black/65"><div className="text-center"><p className="text-[9px] font-black uppercase tracking-[.3em] text-[#d94b2b]">Chapter 02 · Below Ground</p><h2 className="mt-3 text-5xl font-black uppercase">One More Room.</h2><p className="mt-3 text-sm text-zinc-400">The shard led Mara underground. Every room is another step toward the relay.</p><button onClick={start} className="mt-6 bg-[#d94b2b] px-8 py-4 text-[10px] font-black uppercase tracking-[.2em] text-black">Enter</button></div></div>}</div><div className="border-t border-zinc-800 px-4 py-3 text-[9px] font-black uppercase tracking-[.16em] text-zinc-600">Tap an enemy to fire · survive the room · choose an upgrade</div></div>;
}
