"use client";
import {useEffect,useRef,useState} from "react";

type Kind="grunt"|"runner"|"brute"|"boss"; type Enemy={id:number,x:number,y:number,hp:number,maxHp:number,kind:Kind,speed:number}; type Orb={id:number,x:number,y:number,value:number}; type Bullet={id:number,x:number,y:number,vx:number,vy:number,damage:number,pierce:number};
type Build={damage:number,cooldown:number,move:number,magnet:number,armor:number,weapon:number};
const W=960,H=540,DURATION=90;
const WEAPONS=[{name:"RELAY PULSE",damage:14,cooldown:360,count:1,spread:.02},{name:"ARC BURST",damage:9,cooldown:520,count:3,spread:.18},{name:"NOVA RING",damage:20,cooldown:780,count:6,spread:.95}];
const UPGRADES=[
 {id:"pulse",title:"RELAY PULSE",text:"Switch to a rapid single bolt."},
 {id:"arc",title:"ARC BURST",text:"Fire three bolts in a fan."},
 {id:"nova",title:"NOVA RING",text:"Fire a heavy six-bolt burst."},
 {id:"damage",title:"HOTTER CELLS",text:"+25% weapon damage."},
 {id:"cooldown",title:"QUICK FEED",text:"Fire 18% faster."},
 {id:"move",title:"SPRINT RIG",text:"Move 15% faster."},
 {id:"magnet",title:"SHARD MAGNET",text:"Collect XP from farther away."},
 {id:"armor",title:"IMPACT PLATE",text:"Take 20% less contact damage."},
];
export default function OneMoreRoom(){
 const canvas=useRef<HTMLCanvasElement>(null),keys=useRef(new Set<string>()),touch=useRef({x:0,y:0,active:false}),id=useRef(0),build=useRef<Build>({damage:1,cooldown:1,move:1,magnet:1,armor:1,weapon:0});
 const [started,setStarted]=useState(false),[dead,setDead]=useState(false),[won,setWon]=useState(false),[paused,setPaused]=useState(false),[level,setLevel]=useState(1),[xp,setXp]=useState(0),[need,setNeed]=useState(20),[hp,setHp]=useState(100),[maxHp,setMaxHp]=useState(100),[score,setScore]=useState(0),[time,setTime]=useState(0),[upgrade,setUpgrade]=useState(false),[upgradeChoices,setUpgradeChoices]=useState<typeof UPGRADES>([]),[wave,setWave]=useState(1),[bossHp,setBossHp]=useState(0),[notice,setNotice]=useState("RELAY 9 // SECURITY COMPLEX");
 const start=()=>{build.current={damage:1,cooldown:1,move:1,magnet:1,armor:1,weapon:0};setStarted(true);setDead(false);setWon(false);setPaused(false);setUpgrade(false);setLevel(1);setXp(0);setNeed(20);setHp(100);setMaxHp(100);setScore(0);setTime(0);setWave(1);setBossHp(0);setNotice("RELAY 9 // SECURITY COMPLEX");};
 useEffect(()=>{const d=(e:KeyboardEvent)=>{keys.current.add(e.key.toLowerCase());if(e.key==="Escape")setPaused(v=>!v)},u=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener("keydown",d);addEventListener("keyup",u);return()=>{removeEventListener("keydown",d);removeEventListener("keyup",u)}},[]);
 const choose=(u:typeof UPGRADES[number])=>{const b=build.current;if(u.id==="pulse")b.weapon=0;if(u.id==="arc")b.weapon=1;if(u.id==="nova")b.weapon=2;if(u.id==="damage")b.damage*=1.25;if(u.id==="cooldown")b.cooldown*=.82;if(u.id==="move")b.move*=1.15;if(u.id==="magnet")b.magnet*=1.45;if(u.id==="armor")b.armor*=.8;setUpgrade(false);setNotice(`UPGRADE INSTALLED // ${u.title}`)};
 useEffect(()=>{if(!started||dead||won)return;const c=canvas.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;let raf=0,last=performance.now(),elapsed=0,spawnClock=0,fireClock=0,boss=false,bossDefeated=false;let p={x:W/2,y:H/2};let enemies:Enemy[]=[],orbs:Orb[]=[],bullets:Bullet[]=[];let hpv=100,xpv=0,level=1,needv=20,scorev=0,phase=1;
 const nid=()=>++id.current;const spawn=(kind?:Kind,count=1)=>{for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,d=470+Math.random()*130,x=Math.max(20,Math.min(W-20,p.x+Math.cos(a)*d)),y=Math.max(65,Math.min(H-25,p.y+Math.sin(a)*d));const k=kind??(Math.random()<.12?"runner":Math.random()<.16?"brute":"grunt");const scale=1+elapsed*.008;const base=k==="runner"?18:k==="brute"?65:32;enemies.push({id:nid(),x,y,kind:k,hp:base*scale,maxHp:base*scale,speed:k==="runner"?1.9:k==="brute"?.55:1});}};
 const fire=()=>{if(!enemies.length)return;const target=[...enemies].sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0],w=WEAPONS[build.current.weapon],a=Math.atan2(target.y-p.y,target.x-p.x);for(let i=0;i<w.count;i++){const ang=a+(i-(w.count-1)/2)*w.spread;bullets.push({id:nid(),x:p.x,y:p.y,vx:Math.cos(ang)*8,vy:Math.sin(ang)*8,damage:w.damage*build.current.damage,pierce:build.current.weapon===2?2:0});}};
 const frame=(now:number)=>{const dt=Math.min(2,(now-last)/16.67);last=now;if(!paused&&!upgrade){elapsed+=dt/60;spawnClock+=dt*16.67;fireClock+=dt*16.67;const b=build.current;let dx=(keys.current.has("d")||keys.current.has("arrowright")?1:0)-(keys.current.has("a")||keys.current.has("arrowleft")?1:0),dy=(keys.current.has("s")||keys.current.has("arrowdown")?1:0)-(keys.current.has("w")||keys.current.has("arrowup")?1:0);if(touch.current.active){dx=touch.current.x;dy=touch.current.y}const l=Math.hypot(dx,dy)||1;p.x=Math.max(35,Math.min(W-35,p.x+dx/l*3.3*b.move*dt));p.y=Math.max(70,Math.min(H-35,p.y+dy/l*3.3*b.move*dt));
  const newPhase=Math.min(5,1+Math.floor(elapsed/18));if(newPhase!==phase){phase=newPhase;setWave(phase);setNotice(`WAVE ${phase} // SECURITY RESPONSE ESCALATING`)}if(!boss&&elapsed>=60){boss=true;spawn("boss");setNotice("WARNING // RELAY WARDEN DEPLOYED");}
  if(!boss&&spawnClock>Math.max(190,680-elapsed*4)){spawnClock=0;spawn(undefined,Math.min(phase+1,7));}
  if(fireClock>WEAPONS[b.weapon].cooldown*b.cooldown){fireClock=0;fire();}
  bullets=bullets.map(q=>({...q,x:q.x+q.vx*dt,y:q.y+q.vy*dt})).filter(q=>q.x>-30&&q.x<W+30&&q.y>45&&q.y<H+30);
  for(const e of enemies){const a=Math.atan2(p.y-e.y,p.x-e.x);e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;if(Math.hypot(p.x-e.x,p.y-e.y)<25)hpv=Math.max(0,hpv-(e.kind==="boss"?18:e.kind==="brute"?8:4)*b.armor*dt/18);}
  for(const q of bullets){for(const e of enemies){if(Math.hypot(e.x-q.x,e.y-q.y)<(e.kind==="boss"?34:20)){e.hp-=q.damage;if(q.pierce>0)q.pierce--;else q.x=-999;if(e.hp<=0){orbs.push({id:nid(),x:e.x,y:e.y,value:e.kind==="boss"?60:e.kind==="brute"?5:e.kind==="runner"?2:1});scorev+=e.kind==="boss"?1000:e.kind==="brute"?30:10;}}if(q.x===-999)break;}}
  bullets=bullets.filter(q=>q.x>-500);enemies=enemies.filter(e=>e.hp>0);if(boss&&!enemies.some(e=>e.kind==="boss")){bossDefeated=true;setBossHp(0);setWon(true);setNotice("RELAY 9 // CONNECTION ESTABLISHED");cancelAnimationFrame(raf);return;}
  orbs=orbs.filter(o=>{const d=Math.hypot(o.x-p.x,o.y-p.y);if(d<75*b.magnet){o.x+=(p.x-o.x)*.12*dt;o.y+=(p.y-o.y)*.12*dt}if(Math.hypot(o.x-p.x,o.y-p.y)<18){xpv+=o.value;return false}return true});
  if(xpv>=needv){xpv-=needv;needv=Math.floor(needv*1.42);level++;const pool=[...UPGRADES].sort(()=>Math.random()-.5).slice(0,3);setLevel(level);setXp(xpv);setNeed(needv);setUpgradeChoices(pool);setUpgrade(true);cancelAnimationFrame(raf);return;}
  if(hpv<=0){setDead(true);cancelAnimationFrame(raf);return;}if(boss){const be=enemies.find(e=>e.kind==="boss");if(be)setBossHp(be.hp);}
  setTime(Math.floor(elapsed));setHp(Math.round(hpv));setXp(Math.floor(xpv));setScore(scorev);setLevel(level);
 }
 ctx.clearRect(0,0,W,H);const g=ctx.createRadialGradient(p.x,p.y,20,p.x,p.y,700);g.addColorStop(0,"#1a2431");g.addColorStop(1,"#06080b");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle="#202731";for(let x=0;x<W;x+=48){ctx.beginPath();ctx.moveTo(x,55);ctx.lineTo(x,H);ctx.stroke()}for(let y=55;y<H;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()};orbs.forEach(o=>{ctx.fillStyle="#f3d36a";ctx.beginPath();ctx.arc(o.x,o.y,5,0,7);ctx.fill()});bullets.forEach(q=>{ctx.fillStyle=WEAPONS[build.current.weapon].colour;ctx.beginPath();ctx.arc(q.x,q.y,4,0,7);ctx.fill()});enemies.forEach(e=>{ctx.fillStyle=e.kind==="boss"?"#d94b2b":e.kind==="brute"?"#6e3940":e.kind==="runner"?"#9ba1a8":"#565e69";const r=e.kind==="boss"?35:e.kind==="brute"?20:13;ctx.beginPath();ctx.arc(e.x,e.y,r,0,7);ctx.fill();ctx.fillStyle="#151719";ctx.fillRect(e.x-r,e.y-r-9,r*2,4);ctx.fillStyle="#d94b2b";ctx.fillRect(e.x-r,e.y-r-9,r*2*Math.max(0,e.hp/e.maxHp),4)});ctx.fillStyle="#d94b2b";ctx.fillRect(p.x-13,p.y-18,26,35);ctx.fillStyle="#b77b5a";ctx.beginPath();ctx.arc(p.x,p.y-29,11,0,7);ctx.fill();ctx.fillStyle="#16181b";ctx.fillRect(p.x-12,p.y-39,24,7);ctx.fillStyle="#f1ede5";ctx.font="900 14px Arial";ctx.fillText(`COURIER 17   LV ${level}`,20,27);ctx.fillStyle="#555c66";ctx.fillText(`${Math.min(DURATION,Math.floor(elapsed))}/${DURATION}s`,W-75,27);ctx.fillStyle="#161a20";ctx.fillRect(20,40,250,8);ctx.fillStyle="#d94b2b";ctx.fillRect(20,40,250*Math.max(0,hpv/100),8);ctx.fillStyle="#161a20";ctx.fillRect(20,53,250,6);ctx.fillStyle="#f3d36a";ctx.fillRect(20,53,250*Math.min(1,xpv/needv),6);if(boss){ctx.fillStyle="#161a20";ctx.fillRect(W/2-220,34,440,9);ctx.fillStyle="#d94b2b";ctx.fillRect(W/2-220,34,440*Math.max(0,bossHp/900),9);ctx.fillStyle="#f3d36a";ctx.font="900 10px Arial";ctx.fillText("RELAY WARDEN",W/2-43,29)}raf=requestAnimationFrame(frame)};raf=requestAnimationFrame(frame);return()=>cancelAnimationFrame(raf)},[started,dead,won,paused,upgrade]);
 const touchStart=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect();touch.current={x:((e.clientX-r.left)/r.width-.5)*2,y:((e.clientY-r.top)/r.height-.5)*2,active:true}};
 return <div className="overflow-hidden border border-zinc-800 bg-[#08090b]"><div className="flex justify-between border-b border-zinc-800 px-4 py-3 text-[10px] font-black uppercase tracking-[.2em]"><span>THE LONG RUN · CHAPTER 02</span><span className="text-[#d94b2b]">ONE MORE ROOM</span></div><div className="relative aspect-video bg-black"><canvas ref={canvas} width={W} height={H} className="h-full w-full"/>{!started&&<Overlay title="One More Room" text="The shard led Mara below the city. Survive five escalating waves, evolve your loadout and reach Relay 9." button="ENTER THE COMPLEX" onClick={start}/>} {(dead||won)&&<Overlay title={won?"Relay 9 breached":"Mara is down"} text={won?"The Warden falls. A voice comes through the relay: We know what you carried out of District 7. Get to the car.":"The complex wins this run. The shard survives. Mara doesn't give up."} button={won?"RUN AGAIN":"TRY AGAIN"} onClick={start}/>} {upgrade&&<div className="absolute inset-0 grid place-items-center bg-black/85 p-5"><div className="w-full max-w-2xl text-center"><p className="text-[9px] font-black uppercase tracking-[.35em] text-[#d94b2b]">LEVEL {level} // LOADOUT</p><h2 className="mt-2 text-4xl font-black uppercase">Choose your edge</h2><div className="mt-6 grid gap-3 sm:grid-cols-3">{upgradeChoices.map(u=><button key={u.id} onClick={()=>choose(u)} className="border border-zinc-700 bg-[#0b0d10] p-5 text-left transition hover:-translate-y-1 hover:border-[#d94b2b]"><b className="text-xs uppercase">{u.title}</b><p className="mt-2 text-[10px] leading-4 text-zinc-500">{u.text}</p></button>)}</div></div></div>} {paused&&<div className="absolute inset-0 grid place-items-center bg-black/75"><div className="text-center"><p className="text-[9px] font-black uppercase tracking-[.3em] text-zinc-500">Courier 17</p><h2 className="mt-2 text-4xl font-black uppercase">Paused</h2><button onClick={()=>setPaused(false)} className="mt-6 border border-zinc-700 px-7 py-3 text-[9px] font-black uppercase tracking-widest">Resume</button></div></div>}<div onPointerDown={touchStart} onPointerMove={e=>{if(touch.current.active)touchStart(e)}} onPointerUp={()=>touch.current={x:0,y:0,active:false}} onPointerCancel={()=>touch.current={x:0,y:0,active:false}} className="absolute bottom-4 left-4 h-24 w-24 rounded-full border border-white/15 bg-white/5 sm:hidden"/></div><div className="flex flex-wrap justify-between gap-3 border-t border-zinc-800 px-4 py-3 text-[9px] font-black uppercase tracking-[.16em] text-zinc-600"><span>WASD / arrows / touch</span><span>AUTO-FIRE · XP SHARDS · 3 WEAPONS · 8 UPGRADES</span><span>ESC PAUSE</span></div></div>}
function Overlay({title,text,button,onClick}:{title:string;text:string;button:string;onClick:()=>void}){return <div className="absolute inset-0 grid place-items-center bg-black/78 p-6 text-center"><div className="max-w-xl"><p className="text-[9px] font-black uppercase tracking-[.35em] text-[#d94b2b]">Courier 17 · The Long Run</p><h2 className="mt-3 text-5xl font-black uppercase tracking-[-.04em]">{title}</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-zinc-400">{text}</p><button onClick={onClick} className="mt-7 bg-[#d94b2b] px-8 py-4 text-[10px] font-black uppercase tracking-[.2em] text-black">{button}</button></div></div>}
