"use client";

import { useEffect, useRef, useState } from "react";

type Player = { x:number; y:number; vy:number; onGround:boolean; dash:number };
type Block = { x:number; y:number; w:number; h:number; kind:"roof"|"crate"|"drone" };
const W=960,H=540,GRAVITY=.75;

export default function RooftopRunner(){
 const canvasRef=useRef<HTMLCanvasElement>(null), keys=useRef(new Set<string>());
 const [started,setStarted]=useState(false),[dead,setDead]=useState(false),[score,setScore]=useState(0),[best,setBest]=useState(0),[combo,setCombo]=useState(0),[chapter,setChapter]=useState(1);
 useEffect(()=>{setBest(Number(localStorage.getItem("mara-best")||0));const d=(e:KeyboardEvent)=>{if([" ","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.key))e.preventDefault();keys.current.add(e.key.toLowerCase())},u=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());window.addEventListener("keydown",d);window.addEventListener("keyup",u);return()=>{window.removeEventListener("keydown",d);window.removeEventListener("keyup",u)}},[]);
 useEffect(()=>{if(!started||dead)return;const c=canvasRef.current,ctx=c?.getContext("2d");if(!c||!ctx)return;let raf=0,last=performance.now(),world=0,runScore=0,runCombo=0,spawn=0;const p:Player={x:180,y:382,vy:0,onGround:true,dash:0};let blocks:Block=[];for(let i=0;i<18;i++)blocks.push({x:i*260,y:430-(i%3)*25,w:220,h:110,kind:"roof"});blocks.push({x:760,y:345,w:48,h:85,kind:"crate"},{x:1210,y:310,w:48,h:70,kind:"drone"});
 const jump=()=>{if(p.onGround){p.vy=-14;p.onGround=false;runCombo++;setCombo(runCombo)}};
 const add=()=>{const prev=blocks[blocks.length-1],gap=55+Math.random()*100;blocks.push({x:prev.x+prev.w+gap,y:340+Math.random()*75,w:180+Math.random()*110,h:130,kind:"roof"});if(Math.random()>.55)blocks.push({x:prev.x+prev.w+gap+70,y:290,w:42,h:60,kind:Math.random()>.5?"crate":"drone"})};
 const mara=()=>{const x=p.x,y=p.y;ctx.save();ctx.translate(x,y);ctx.fillStyle="#17191b";ctx.fillRect(-13,18,10,30);ctx.fillRect(3,18,10,30);ctx.fillStyle="#d94b2b";ctx.fillRect(-17,-15,34,38);ctx.fillStyle="#202326";ctx.fillRect(-22,-5,6,24);ctx.fillRect(16,-5,6,24);ctx.fillStyle="#b8bec3";ctx.fillRect(12,-2,23,5);ctx.fillStyle="#b77b5a";ctx.beginPath();ctx.arc(0,-28,13,0,Math.PI*2);ctx.fill();ctx.fillStyle="#17191b";ctx.fillRect(-14,-38,28,8);ctx.restore()};
 const tick=(now:number)=>{const dt=Math.min((now-last)/16.67,2);last=now;const right=keys.current.has("d")||keys.current.has("arrowright"),left=keys.current.has("a")||keys.current.has("arrowleft");if(right)p.x+=3.5*dt;if(left)p.x-=2.5*dt;if(keys.current.has(" ")||keys.current.has("w")||keys.current.has("arrowup"))jump();p.vy+=GRAVITY*dt;p.y+=p.vy*dt;if(p.x>520)world+=2.35*dt;let grounded=false;for(const b of blocks){if(b.kind!=="roof")continue;if(p.x>b.x&&p.x<b.x+b.w&&p.y+48>=b.y&&p.y+48<=b.y+24&&p.vy>=0){p.y=b.y-48;p.vy=0;grounded=true}}p.onGround=grounded;if(!grounded&&p.y>H+70){const s=Math.floor(runScore);setScore(s);setBest(v=>{const n=Math.max(v,s);localStorage.setItem("mara-best",String(n));return n});setDead(true);return}runScore+=.8*dt;spawn+=dt;if(spawn>2.2){add();spawn=0}if(Math.floor(runScore)%500===0&&Math.floor(runScore)>0)setChapter(Math.min(5,1+Math.floor(runScore/500)));
 ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#182842");g.addColorStop(1,"#07090d");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<16;i++){ctx.fillStyle=i%2?"#101824":"#0c121b";const bh=90+(i*43)%190;ctx.fillRect(i*78-(world*.12%78),H-bh-30,62,bh)}ctx.strokeStyle="rgba(217,75,43,.16)";ctx.lineWidth=2;for(let i=0;i<8;i++){ctx.beginPath();ctx.moveTo(120+i*130-(world*.25%130),120);ctx.lineTo(30+i*160-(world*.25%160),380);ctx.stroke()}
 blocks.forEach(b=>{const x=b.x-world;if(x<-150||x>W+150)return;ctx.fillStyle="#252a32";ctx.fillRect(x,b.y,b.w,b.h);ctx.fillStyle="#d94b2b";ctx.fillRect(x,b.y,b.w,4);if(b.kind==="crate"){ctx.fillStyle="#9b694e";ctx.fillRect(x,b.y-36,b.w,36);ctx.strokeStyle="#d4a37c";ctx.strokeRect(x+5,b.y-31,b.w-10,26)}if(b.kind==="drone"){ctx.fillStyle="#c9ced3";ctx.fillRect(x-12,b.y+25,b.w+24,7);ctx.fillStyle="#d94b2b";ctx.fillRect(x+14,b.y+7,18,18)}});
 ctx.fillStyle="#f0e9df";ctx.font="900 16px Arial";ctx.fillText(`COURIER 17   ${String(Math.floor(runScore)).padStart(5,"0")}`,30,38);ctx.fillStyle="#7f8791";ctx.font="700 11px Arial";ctx.fillText(`BEST ${String(best).padStart(5,"0")}   COMBO x${Math.max(1,runCombo)}`,30,58);ctx.fillStyle="#d94b2b";ctx.font="900 10px Arial";ctx.fillText(`CHAPTER 01 / DISTRICT ${chapter}`,W-185,38);mara();ctx.fillStyle="rgba(255,255,255,.38)";ctx.font="900 11px Arial";ctx.fillText("RUN  •  JUMP  •  SURVIVE",W-210,58);raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[started,dead,best]);
 const start=()=>{setDead(false);setScore(0);setCombo(0);setStarted(true)};const press=(k:string)=>{keys.current.add(k);window.setTimeout(()=>keys.current.delete(k),140)};
 return <div className="overflow-hidden border border-zinc-800 bg-[#08090b] shadow-2xl"><div className="relative aspect-[16/9] w-full"><canvas ref={canvasRef} width={W} height={H} className="h-full w-full object-cover"/><div className="pointer-events-none absolute inset-x-0 bottom-3 flex justify-between px-4 opacity-80 sm:hidden"><button aria-label="Move left" onTouchStart={()=>press("arrowleft")} className="pointer-events-auto h-14 w-14 rounded-full border border-white/20 bg-black/50 text-xl">←</button><button aria-label="Jump" onTouchStart={()=>press(" ")} className="pointer-events-auto h-16 w-16 rounded-full border border-[#d94b2b]/60 bg-[#d94b2b]/80 text-[9px] font-black text-black">JUMP</button><button aria-label="Move right" onTouchStart={()=>press("arrowright")} className="pointer-events-auto h-14 w-14 rounded-full border border-white/20 bg-black/50 text-xl">→</button></div>{!started&&<div className="absolute inset-0 grid place-items-center bg-[#07080b]/60 p-6 text-center"><div><p className="text-[10px] font-black uppercase tracking-[.35em] text-[#d94b2b]">The Long Run · Chapter 01</p><h2 className="mt-3 text-5xl font-black uppercase tracking-[-.05em]">Rooftop Runner</h2><p className="mx-auto mt-3 max-w-md text-sm text-zinc-400">Mara has one delivery. The city has one lockdown. Run.</p><button onClick={start} className="mt-7 bg-[#d94b2b] px-8 py-4 text-[10px] font-black uppercase tracking-[.2em] text-black">Start the run</button></div></div>}{dead&&<div className="absolute inset-0 grid place-items-center bg-black/75 p-6 text-center"><div><p className="text-[10px] font-black uppercase tracking-[.35em] text-[#d94b2b]">Courier 17 · Down</p><h2 className="mt-3 text-5xl font-black uppercase">Run over.</h2><p className="mt-3 text-zinc-500">Score {score} · Best {best}</p><button onClick={start} className="mt-7 border border-zinc-700 px-8 py-4 text-[10px] font-black uppercase tracking-[.2em]">Run again</button></div></div>}</div><div className="flex items-center justify-between border-t border-zinc-900 px-4 py-3 text-[9px] font-black uppercase tracking-[.15em] text-zinc-600"><span>Desktop: A/D + Space</span><span>Mobile: touch controls</span></div></div>;
}
