"use client";
import {useEffect,useRef,useState} from "react";
type Enemy={id:number;x:number;y:number;hp:number;max:number;kind:"guard"|"hunter"|"boss"};
type Shot={id:number;x:number;y:number;vx:number;vy:number;damage:number};
const W=960,H=540;
export default function TheFinalRun(){
 const [run,setRun]=useState(false),[win,setWin]=useState(false),[hp,setHp]=useState(100),[energy,setEnergy]=useState(100),[boss,setBoss]=useState(100),[score,setScore]=useState(0),[wave,setWave]=useState(1),[shots,setShots]=useState<Shot[]>([]),[enemies,setEnemies]=useState<Enemy[]>([]),[weapon,setWeapon]=useState(1),[playerX,setPlayerX]=useState(250),[playerY,setPlayerY]=useState(390);
 const keys=useRef(new Set<string>()),id=useRef(0),aim=useRef({x:700,y:270});
 const spawn=(w:number)=>setEnemies(Array.from({length:w<3?4+w:5},(_,i)=>{const b=w===3&&i===0;return{id:++id.current,x:620+Math.random()*250,y:100+Math.random()*330,hp:b?100:w===2?3:2,max:b?100:w===2?3:2,kind:b?"boss":i%2?"hunter":"guard"}}));
 const start=()=>{setRun(true);setWin(false);setHp(100);setEnergy(100);setBoss(100);setScore(0);setWave(1);setWeapon(1);setPlayerX(250);setPlayerY(390);setShots([]);spawn(1)};
 const fire=()=>{if(!run||energy<6)return;setEnergy(v=>Math.max(0,v-6));const target=[...enemies].sort((a,b)=>Math.hypot(a.x-playerX,a.y-playerY)-Math.hypot(b.x-playerX,b.y-playerY))[0];if(target)setShots(s=>[...s,{id:++id.current,x:playerX+30,y:playerY,vx:(target.x-playerX)/18,vy:(target.y-playerY)/18,damage:weapon}])};
 useEffect(()=>{const d=(e:KeyboardEvent)=>{keys.current.add(e.key.toLowerCase());if(e.key===" ")fire()},u=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener("keydown",d);addEventListener("keyup",u);return()=>{removeEventListener("keydown",d);removeEventListener("keyup",u)}},[run,energy,enemies,playerX,playerY,weapon]);
 useEffect(()=>{if(!run||win)return;const t=window.setInterval(()=>{const left=keys.current.has("a")||keys.current.has("arrowleft"),right=keys.current.has("d")||keys.current.has("arrowright"),up=keys.current.has("w")||keys.current.has("arrowup"),down=keys.current.has("s")||keys.current.has("arrowdown");setPlayerX(v=>Math.max(170,Math.min(790,v+(right?5:left?-5:0))));setPlayerY(v=>Math.max(120,Math.min(455,v+(down?5:up?-5:0))));setEnergy(v=>Math.min(100,v+2));setShots(ss=>ss.map(s=>({...s,x:s.x+s.vx,y:s.y+s.vy})).filter(s=>s.x>0&&s.x<W&&s.y>0&&s.y<H));setEnemies(es=>es.map(e=>{const dx=playerX-e.x,dy=playerY-e.y,d=Math.max(1,Math.hypot(dx,dy)),speed=e.kind==="boss"?.25:e.kind==="hunter"?1.15:.85;return{...e,x:e.x+dx/d*speed,y:e.y+dy/d*speed}}).filter(e=>{if(Math.hypot(e.x-playerX,e.y-playerY)<48){setHp(v=>Math.max(0,v-(e.kind==="boss"?18:7)));return false}return true}));setShots(ss=>ss.filter(s=>{const i=enemies.findIndex(e=>Math.hypot(e.x-s.x,e.y-s.y)<32);if(i<0)return true;const e=enemies[i];if(e.kind==="boss")setBoss(v=>Math.max(0,v-s.damage));setEnemies(es=>es.map((x,j)=>j===i?{...x,hp:x.hp-s.damage}:x).filter(x=>x.hp>0));setScore(v=>v+(e.kind==="boss"?100:10));return false}));},50);return()=>clearInterval(t)},[run,win,enemies,playerX,playerY]);
 useEffect(()=>{if(boss<=0){setWin(true);setRun(false);return}if(run&&enemies.length===0){if(wave>=3){setWin(true);setRun(false)}else{const n=wave+1;setWave(n);setWeapon(v=>Math.min(3,v+1));window.setTimeout(()=>spawn(n),500)}}},[enemies.length,run,wave,boss]);
 useEffect(()=>{if(hp<=0&&run){setRun(false);setEnemies([]);setShots([])}},[hp,run]);
 const aimAt=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect();aim.current={x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H};fire()};
 return <div className="overflow-hidden border border-zinc-800 bg-[#08090b]"><div className="flex justify-between border-b border-zinc-800 px-4 py-3 text-[10px] font-black uppercase tracking-[.2em]"><span>THE LONG RUN · CHAPTER 05</span><span className="text-[#d94b2b]">THE FINAL RUN</span></div><div onPointerDown={aimAt} className="relative aspect-video overflow-hidden bg-[#100d11] touch-none select-none"><div className="absolute inset-[5%] border-[12px] border-[#302933] bg-[#09090c] shadow-[inset_0_0_160px_rgba(140,40,70,.28)]"/><div className="absolute left-[7%] top-[9%] h-5 w-48 bg-[#d94b2b]/80"/><div className="absolute right-[8%] top-[9%] h-3 w-32 bg-zinc-600"/><div className="absolute" style={{left:`${playerX/W*100}%`,top:`${playerY/H*100}%`}}><div className="h-28 w-12 -translate-x-1/2 bg-[#d94b2b] shadow-[8px_8px_0_#181419]"/><div className="absolute -top-7 left-1/2 h-9 w-9 -translate-x-1/2 rounded-full bg-[#b77b5a]"/></div>{enemies.map(e=><div key={e.id} className={`absolute -translate-x-1/2 -translate-y-1/2 ${e.kind==="boss"?"h-28 w-24 bg-[#8d2949]":"h-10 w-8 bg-zinc-600"}`} style={{left:`${e.x/W*100}%`,top:`${e.y/H*100}%`}}><span className="absolute -top-3 left-0 h-2 w-full bg-black"><span className="block h-full bg-[#d94b2b]" style={{width:`${e.kind==="boss"?boss:e.hp/e.max*100}%`}}/></span></div>)}{shots.map(s=><div key={s.id} className="absolute h-2 w-5 rounded bg-[#f3d36a]" style={{left:`${s.x/W*100}%`,top:`${s.y/H*100}%`}}/>)}<div className="absolute left-4 top-4 flex flex-wrap gap-2 text-[9px] font-black uppercase tracking-widest"><span className="bg-black/80 px-2 py-1">HP {hp}</span><span className="bg-black/80 px-2 py-1">ENERGY {energy}</span><span className="bg-black/80 px-2 py-1">WAVE {wave}/3</span><span className="bg-black/80 px-2 py-1">WEAPON {weapon}</span><span className="bg-black/80 px-2 py-1">SCORE {score}</span></div>{wave===3&&run&&<div className="absolute left-1/2 top-3 w-1/3 -translate-x-1/2"><p className="mb-1 text-center text-[8px] font-black uppercase tracking-widest">MERIDIAN DIRECTOR</p><div className="h-2 bg-black"><div className="h-full bg-[#d94b2b]" style={{width:`${boss}%`}}/></div></div>}{!run&&!win&&<Overlay title="The Final Run" text="Meridian Tower. The shard has unlocked the core. Mara goes in alone. Three security phases. One source. No way back." button="ENTER MERIDIAN" onClick={start}/>} {!run&&win&&<Overlay title="The Long Run" text={`The Director falls. The shard opens. Score ${score}. Mara finally sees who sent Courier 17 running in the first place.`} button="PLAY THE WHOLE STORY AGAIN" onClick={start}/>} {!run&&!win&&hp<=0&&<Overlay title="Not Yet." text="Meridian closes its doors. Mara keeps the shard. The run isn't over." button="RUN AGAIN" onClick={start}/>}</div><div className="flex justify-between border-t border-zinc-800 px-4 py-3 text-[9px] font-black uppercase tracking-[.16em] text-zinc-600"><span>Move: WASD · arrows</span><span>Space / tap: pulse</span></div></div>}
function Overlay({title,text,button,onClick}:{title:string;text:string;button:string;onClick:()=>void}){return <div className="absolute inset-0 grid place-items-center bg-black/80 p-6 text-center"><div className="max-w-xl"><p className="text-[9px] font-black uppercase tracking-[.3em] text-[#d94b2b]">Courier 17 · Meridian Tower</p><h2 className="mt-3 text-5xl font-black uppercase">{title}</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-zinc-400">{text}</p><button onClick={onClick} className="mt-7 bg-[#d94b2b] px-8 py-4 text-[10px] font-black uppercase tracking-[.2em] text-black">{button}</button></div></div>}
