using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;

namespace SmallGameLab.TheLongRun
{
    public sealed class FiveChapterGame : MonoBehaviour
    {
        private readonly List<GameObject> world = new List<GameObject>();
        private readonly List<GameObject> enemies = new List<GameObject>();
        private readonly List<GameObject> shots = new List<GameObject>();
        private Camera cam; private Canvas canvas; private Text header, hud, objective; private Transform mara, gun; private Sprite sprite;
        private int chapter, hp, kills, score, wave; private float time, distance, spawn, fire, bossHp; private bool playing, dead, won, boss;
        private static readonly string[] Titles = {"THE DELIVERY","ONE MORE ROOM","THE GETAWAY","DUNGEON 7","THE FINAL RUN"};
        private static readonly string[] Places = {"DISTRICT 7 ROOFTOPS","RELAY 9 UNDERGROUND","BLACKLINE PURSUIT","THE WARDEN'S VAULT","THE LAST CITY"};
        private Color ember = new Color(.96f,.25f,.09f), gold = new Color(1f,.72f,.22f);
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)] static void Boot(){ if(FindFirstObjectByType<FiveChapterGame>()==null) new GameObject("THE LONG RUN · GAME ROOT").AddComponent<FiveChapterGame>(); }
        void Start(){ Application.targetFrameRate=60; sprite=Sprite.Create(Texture2D.whiteTexture,new Rect(0,0,1,1),new Vector2(.5f,.5f)); BuildCamera(); BuildUI(); BuildMara(); ShowChapter(); }
        GameObject Box(string n,Vector2 p,Vector2 s,Color c,int order=0){var g=new GameObject(n);g.transform.position=p;g.transform.localScale=s;var r=g.AddComponent<SpriteRenderer>();r.sprite=sprite;r.color=c;r.sortingOrder=order;world.Add(g);return g;}
        void BuildCamera(){cam=new GameObject("Main Camera").AddComponent<Camera>();cam.orthographic=true;cam.orthographicSize=5.1f;cam.transform.position=new Vector3(0,0,-20);}
        void BuildMara(){mara=new GameObject("Mara Vale · Courier 17").transform;mara.position=new Vector3(-3,-1.3f,0);var r=mara.gameObject.AddComponent<SpriteRenderer>();r.sprite=Resources.Load<Sprite>("Art/Mara/mara");if(!r.sprite)r.sprite=sprite;r.sortingOrder=40;mara.localScale=Vector3.one*.55f;gun=new GameObject("RAVEN SMG").transform;gun.SetParent(mara,false);gun.localPosition=new Vector3(.75f,0,-.1f);var w=gun.gameObject.AddComponent<SpriteRenderer>();w.sprite=Resources.Load<Sprite>("Art/Weapons/raven-smg");if(!w.sprite)w.sprite=sprite;w.sortingOrder=45;gun.localScale=Vector3.one*.012f;}
        Text Label(string n,Vector2 p,Vector2 size,int fs,TextAnchor a){var g=new GameObject(n);g.transform.SetParent(canvas.transform,false);var r=g.AddComponent<RectTransform>();r.anchorMin=r.anchorMax=new Vector2(.5f,1);r.pivot=new Vector2(.5f,1);r.anchoredPosition=p;r.sizeDelta=size;var t=g.AddComponent<Text>();t.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");t.fontSize=fs;t.fontStyle=FontStyle.Bold;t.alignment=a;return t;}
        void BuildUI(){canvas=new GameObject("HUD").AddComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;var s=canvas.gameObject.AddComponent<CanvasScaler>();s.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;s.referenceResolution=new Vector2(1920,1080);canvas.gameObject.AddComponent<GraphicRaycaster>();header=Label("Header",new Vector2(0,-25),new Vector2(1800,50),26,TextAnchor.MiddleLeft);hud=Label("HUD",new Vector2(0,-68),new Vector2(1800,35),16,TextAnchor.MiddleLeft);objective=Label("Objective",new Vector2(0,-105),new Vector2(1700,35),14,TextAnchor.MiddleCenter);objective.color=gold;}
        void BuildWorld(){foreach(var g in world)if(g)Destroy(g);world.Clear();foreach(var g in enemies)if(g)Destroy(g);enemies.Clear();foreach(var g in shots)if(g)Destroy(g);shots.Clear();Color bg=new Color(.02f,.045f,.08f);if(chapter==1)bg=new Color(.01f,.02f,.035f);if(chapter==2)bg=new Color(.06f,.02f,.015f);if(chapter==3)bg=new Color(.03f,.01f,.05f);if(chapter==4)bg=new Color(.07f,.01f,.02f);cam.backgroundColor=bg;Box("Sky",new Vector2(10,2),new Vector2(70,14),bg,-50);for(int i=-20;i<45;i++){float h=2.5f+Mathf.Abs(Mathf.Sin(i*1.73f))*5f;Box("Tower",new Vector2(i*2,-2.1f+h*.5f),new Vector2(1.55f,h),new Color(.035f,.05f,.08f),-30);for(int r=0;r<5;r++)Box("Window",new Vector2(i*2-.35f,-1.1f+r*.75f),new Vector2(.14f,.2f),new Color(1f,.55f,.16f,.65f),-29);}Box("Street",new Vector2(10,-2.6f),new Vector2(70,.7f),new Color(.055f,.065f,.08f),2);Box("Edge",new Vector2(10,-2.24f),new Vector2(70,.05f),ember,3);for(int i=-8;i<40;i++)Box("Lamp",new Vector2(i*3.4f,-1f),new Vector2(.05f,2.2f),new Color(.1f,.13f,.17f),4);if(chapter==0||chapter==4)for(int i=0;i<15;i++)Box("Roof",new Vector2(3+i*3.6f,-1.4f+Mathf.Sin(i*.8f)*.3f),new Vector2(2.4f,.18f),new Color(.12f,.14f,.18f),6);}
        void ShowChapter(){playing=false;dead=won=boss=false;BuildWorld();header.text="CHAPTER "+(chapter+1).ToString("00")+"  //  "+Titles[chapter];objective.text=Places[chapter];ShowPanel(Titles[chapter],"Mara takes a courier job across District 7. The package is not ordinary.","START CHAPTER",StartChapter);}
        void ShowPanel(string h,string b,string button,UnityEngine.Events.UnityAction action){var old=canvas.transform.Find("Overlay");if(old)Destroy(old.gameObject);var p=new GameObject("Overlay");p.transform.SetParent(canvas.transform,false);var r=p.AddComponent<RectTransform>();r.anchorMin=r.anchorMax=new Vector2(.5f,.5f);r.pivot=new Vector2(.5f,.5f);r.sizeDelta=new Vector2(900,430);var bg=p.AddComponent<Image>();bg.color=new Color(.006f,.01f,.018f,.98f);var t=Label("Heading",new Vector2(0,-90),new Vector2(800,70),46,TextAnchor.MiddleCenter);t.transform.SetParent(p.transform,false);t.text=h;var body=Label("Body",new Vector2(0,-175),new Vector2(760,90),18,TextAnchor.MiddleCenter);body.transform.SetParent(p.transform,false);body.text=b;body.color=new Color(.7f,.74f,.8f);var go=new GameObject("StartButton");go.transform.SetParent(p.transform,false);var br=go.AddComponent<RectTransform>();br.anchorMin=br.anchorMax=new Vector2(.5f,0);br.pivot=new Vector2(.5f,0);br.anchoredPosition=new Vector2(0,45);br.sizeDelta=new Vector2(340,68);var im=go.AddComponent<Image>();im.color=ember;var bu=go.AddComponent<Button>();bu.onClick.AddListener(action);var lab=Label("Label",Vector2.zero,new Vector2(340,68),17,TextAnchor.MiddleCenter);lab.transform.SetParent(go.transform,false);lab.text=button;lab.color=Color.black;}
        void StartChapter(){var o=canvas.transform.Find("Overlay");if(o)Destroy(o.gameObject);playing=true;hp=100;kills=score=wave=0;time=distance=0;spawn=.3f;fire=.05f;bossHp=600;mara.position=new Vector3(-3,-1.3f,0);objective.text=Goal();}
        string Goal(){if(chapter==0)return "REACH EXTRACTION · A/D OR ARROWS · SPACE/W JUMP · AUTO-FIRE";if(chapter==1)return "SURVIVE 6 WAVES · TAKEDOWNS POWER YOUR LOADOUT";if(chapter==2)return "LOSE THE HEAT · REACH 2,000m";if(chapter==3)return "28 TAKEDOWNS · DEFEAT THE WARDEN";return "DEFEAT THE ARCHITECT · COMPLETE MARA'S RUN";}
        void Update(){if(!playing)return;float dt=Mathf.Min(Time.deltaTime,.033f);time+=dt;distance+=dt*5.4f;InputStep(dt);Sim(dt);cam.transform.position=Vector3.Lerp(cam.transform.position,new Vector3(mara.position.x+2.2f,.1f,-20),1-Mathf.Exp(-7*dt));hud.text="HP "+hp.ToString("000")+"   SCORE "+score.ToString("000000")+"   TAKEDOWNS "+kills.ToString("00")+"   WAVE "+wave.ToString("00")+"   DIST "+distance.ToString("0000")+"m";if(boss)objective.text="BOSS // "+Mathf.Max(0,bossHp).ToString("000")+" HP";if(dead){playing=false;ShowPanel("MARA IS DOWN","The shard is still in Mara's hand. One more run.","RETRY",StartChapter);}if(won){playing=false;if(chapter<4){chapter++;ShowChapter();}else ShowPanel("RUN COMPLETE","Five chapters. One courier. The story is only beginning.","PLAY AGAIN",()=>{chapter=0;ShowChapter();});}}
        void InputStep(float dt){var k=Keyboard.current;if(k==null)return;float x=(k.dKey.isPressed||k.rightArrowKey.isPressed?1f:0f)-(k.aKey.isPressed||k.leftArrowKey.isPressed?1f:0f);mara.position+=new Vector3(x*7f*dt,0,0);mara.position=new Vector3(Mathf.Clamp(mara.position.x,-7.3f,7.3f),Mathf.Clamp(mara.position.y,-1.3f,2f),0);if((k.spaceKey.wasPressedThisFrame||k.wKey.wasPressedThisFrame||k.upArrowKey.wasPressedThisFrame)&&mara.position.y<=-1.25f)mara.position+=Vector3.up*1.1f;if(k.enterKey.wasPressedThisFrame||k.eKey.wasPressedThisFrame)Fire();}
        void Sim(float dt){fire-=dt;spawn-=dt;if(fire<=0){Fire();fire=chapter==1 ? .16f : .23f;}if(spawn<=0){Spawn();spawn=Mathf.Max(.35f,1.1f-time*.01f);}MoveShots(dt);MoveEnemies(dt);if(chapter==0&&distance>48)won=true;if(chapter==2&&distance>370)won=true;if(chapter==1&&wave>=6)won=true;if(chapter==3&&kills>=28&&!boss){boss=true;SpawnBoss();}if(chapter==4&&time>12&&!boss){boss=true;SpawnBoss();}if(boss&&bossHp<=0)won=true;if(chapter==1)wave=Mathf.Clamp(kills/6,0,6);}
        void Fire(){if(!playing)return;var g=Box("Projectile",mara.position+new Vector2(.95f,.05f),new Vector2(1.15f,.08f),chapter==2?gold:ember,50);shots.Add(g);var fx=Box("MuzzleFlash",mara.position+new Vector2(.95f,0),new Vector2(.28f,.12f),gold,51);Destroy(fx,.1f);}
        void MoveShots(float dt){for(int i=shots.Count-1;i>=0;i--){var s=shots[i];if(!s){shots.RemoveAt(i);continue;}s.transform.position+=Vector3.right*18f*dt;bool hit=s.transform.position.x>15;for(int e=enemies.Count-1;e>=0&&!hit;e--){var a=enemies[e];if(!a)continue;if(Vector2.Distance(s.transform.position,a.transform.position)<1.1f){hit=true;if(a.name=="BOSS")bossHp-=25;else{kills++;score+=100;Destroy(a);enemies.RemoveAt(e);}}}if(hit){Destroy(s);shots.RemoveAt(i);}}}
        void MoveEnemies(float dt){for(int i=enemies.Count-1;i>=0;i--){var e=enemies[i];if(!e){enemies.RemoveAt(i);continue;}float speed=e.name=="BOSS"?.75f:chapter==2?5.4f:1.9f;e.transform.position+=Vector3.left*speed*dt;if(Vector2.Distance(e.transform.position,mara.position)<1f){hp-=e.name=="BOSS"?20:9;Destroy(e);enemies.RemoveAt(i);if(hp<=0){dead=true;return;}}else if(e.transform.position.x<-11){Destroy(e);enemies.RemoveAt(i);}}}
        void Spawn(){if(chapter==2){var c=Box("Enemy Car",new Vector2(9,Random.Range(-1.6f,.8f)),new Vector2(2.1f,.72f),new Color(.62f,.05f,.08f),35);Box("Headlight",c.transform.position+new Vector3(.85f,.08f,0),new Vector2(.13f,.15f),gold,36);enemies.Add(c);return;}Color c2=chapter==3?new Color(.56f,.16f,.78f):chapter==4?new Color(.72f,.07f,.12f):new Color(.12f,.38f,.48f);enemies.Add(Box("Enemy",new Vector2(9,Random.Range(-1.6f,1.2f)),chapter==3?new Vector2(1.15f,1.8f):new Vector2(.85f,1f),c2,35));}
        void SpawnBoss(){enemies.Add(Box("BOSS",new Vector2(6.2f,.1f),new Vector2(2.8f,3f),chapter==4?new Color(.72f,.06f,.1f):new Color(.44f,.15f,.68f),38));}
    }
}
