using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.UI;

namespace SmallGameLab.TheLongRun
{
    public sealed class FiveChapterGame : MonoBehaviour
    {
        enum Chapter { Delivery, Complex, Getaway, Vault, Final }
        sealed class Actor { public GameObject go; public int hp; public bool boss; }
        sealed class Shot { public GameObject go; public float speed; public int damage; }
        static readonly string[] Titles={"THE DELIVERY","ONE MORE ROOM","THE GETAWAY","DUNGEON 7","THE FINAL RUN"};
        static readonly string[] Places={"DISTRICT 7 ROOFTOPS","RELAY 9 UNDERGROUND","BLACKLINE PURSUIT","THE WARDEN'S VAULT","THE LAST CITY"};
        readonly List<GameObject> scenery=new(); readonly List<Actor> enemies=new(); readonly List<Shot> shots=new();
        Transform mara,gun; Camera cam; Canvas ui; Text title,hud,goal; GameObject panel; Sprite pixel;
        Chapter chapter; float t,distance,spawn,fire,bossHp; int hp,kills,score,wave; bool running,dead,won,bossActive; Vector2 velocity;
        readonly Color ember=new(.96f,.25f,.09f), gold=new(1f,.72f,.22f), dark=new(.006f,.01f,.018f);

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)] static void Boot(){if(FindFirstObjectByType<FiveChapterGame>()==null)new GameObject("THE LONG RUN · GAME ROOT").AddComponent<FiveChapterGame>();}
        void Start(){Application.targetFrameRate=60;pixel=Sprite.Create(Texture2D.whiteTexture,new Rect(0,0,1,1),Vector2.one*.5f);BuildCamera();BuildUI();BuildMara();ShowChapter();}
        GameObject Box(string n,Vector2 p,Vector2 s,Color c,int order=0){var g=new GameObject(n);g.transform.position=p;g.transform.localScale=s;var r=g.AddComponent<SpriteRenderer>();r.sprite=pixel;r.color=c;r.sortingOrder=order;scenery.Add(g);return g;}
        void BuildCamera(){cam=new GameObject("Main Camera").AddComponent<Camera>();cam.orthographic=true;cam.orthographicSize=5.1f;cam.transform.position=new Vector3(0,0,-20);cam.backgroundColor=dark;}
        void BuildMara(){mara=new GameObject("Mara Vale · Courier 17").transform;mara.position=new Vector3(-3,-1.3f,0);var r=mara.gameObject.AddComponent<SpriteRenderer>();r.sprite=Resources.Load<Sprite>("Art/Mara/mara")??pixel;r.sortingOrder=40;mara.localScale=Vector3.one*.55f;gun=new GameObject("RAVEN SMG").transform;gun.SetParent(mara,false);gun.localPosition=new Vector3(.75f,0,-.1f);var wr=gun.gameObject.AddComponent<SpriteRenderer>();wr.sprite=Resources.Load<Sprite>("Art/Weapons/raven-smg")??pixel;wr.sortingOrder=45;gun.localScale=Vector3.one*.012f;}
        void BuildWorld(){foreach(var g in scenery)if(g)Destroy(g);scenery.Clear();foreach(var e in enemies)if(e.go)Destroy(e.go);enemies.Clear();foreach(var s in shots)if(s.go)Destroy(s.go);shots.Clear();Color bg=chapter switch{Chapter.Delivery=>new(.02f,.045f,.08f),Chapter.Complex=>new(.01f,.02f,.035f),Chapter.Getaway=>new(.06f,.02f,.015f),Chapter.Vault=>new(.03f,.01f,.05f),_=>new(.07f,.01f,.02f)};cam.backgroundColor=bg;Box("Sky",new Vector2(10,2),new Vector2(65,14),bg,-50);for(int i=-20;i<44;i++){float h=2.5f+Mathf.Abs(Mathf.Sin(i*1.73f))*5.2f;Box("Tower",new Vector2(i*2,-2.1f+h*.5f),new Vector2(1.55f,h),new(.035f,.05f,.08f),-30);for(int r=0;r<6;r++)for(int c=0;c<2;c++)if((i+r+c)%3!=0)Box("Window",new Vector2(i*2-.36f+c*.7f,-1.3f+r*.72f),new(.14f,.2f),new(1f,.55f,.16f,.65f),-29);}Box("Road",new Vector2(10,-2.6f),new Vector2(65,.7f),new(.055f,.065f,.08f),2);Box("RoadEdge",new Vector2(10,-2.24f),new Vector2(65,.05f),ember,3);for(int i=-8;i<40;i++){Box("Lamp",new Vector2(i*3.4f,-1.1f),new(.05f,2.3f),new(.11f,.14f,.18f),4);Box("LampGlow",new Vector2(i*3.4f,.05f),new(.3f,.08f),ember,5);}if(chapter==Chapter.Delivery||chapter==Chapter.Final)for(int i=0;i<15;i++)Box("Rooftop",new Vector2(3+i*3.6f,-1.4f+Mathf.Sin(i*.8f)*.3f),new(2.4f,.18f),new(.12f,.14f,.18f),6);if(chapter==Chapter.Vault)for(int i=0;i<13;i++){Box("Pillar",new Vector2(-12+i*3.2f,.2f),new(.3f,5f),new(.12f,.04f,.18f),6);Box("Energy",new Vector2(-10.4f+i*3.2f,2.2f),new(2.7f,.05f),new(.6f,.12f,.8f),7);}}
        void BuildUI(){ui=new GameObject("HUD").AddComponent<Canvas>();ui.renderMode=RenderMode.ScreenSpaceOverlay;var s=ui.gameObject.AddComponent<CanvasScaler>();s.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;s.referenceResolution=new Vector2(1920,1080);ui.gameObject.AddComponent<GraphicRaycaster>();if(!FindFirstObjectByType<EventSystem>())new GameObject("EventSystem",typeof(EventSystem),typeof(InputSystemUIInputModule));title=Text("Title",new Vector2(0,-28),new Vector2(1800,50),26,TextAnchor.MiddleLeft);hud=Text("HUD",new Vector2(0,-70),new Vector2(1800,36),16,TextAnchor.MiddleLeft);goal=Text("Goal",new Vector2(0,-108),new Vector2(1700,36),14,TextAnchor.MiddleCenter);goal.color=gold;}
        Text Text(string n,Vector2 p,Vector2 size,int fs,TextAnchor a){var g=new GameObject(n);g.transform.SetParent(ui.transform,false);var r=g.AddComponent<RectTransform>();r.anchorMin=r.anchorMax=new Vector2(.5f,1);r.pivot=new Vector2(.5f,1);r.anchoredPosition=p;r.sizeDelta=size;var x=g.AddComponent<Text>();x.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");x.fontSize=fs;x.fontStyle=FontStyle.Bold;x.alignment=a;x.raycastTarget=false;return x;}
        Text Child(GameObject p,string n,Vector2 pos,Vector2 size,int fs,TextAnchor a){var x=Text(n,pos,size,fs,a);x.transform.SetParent(p.transform,false);return x;}
        void ShowChapter(){running=false;dead=won=bossActive=false;BuildWorld();title.text=$"CHAPTER {(int)chapter+1:00}  //  {Titles[(int)chapter]}";goal.text=Places[(int)chapter];string body=chapter switch{Chapter.Delivery=>"Mara takes an ordinary courier job across District 7. The package is not ordinary.",Chapter.Complex=>"The shard leads Mara below the city. Survive the rooms and reach Relay 9.",Chapter.Getaway=>"Blackline has eyes everywhere. Take the car, break the pursuit and keep moving.",Chapter.Vault=>"The Warden controls the vault. Breach it, survive the room and take the truth.",_=>"The network is exposed. One final run decides whether the city survives."};panel=Panel(Titles[(int)chapter],body,"START CHAPTER",StartChapter);}
        GameObject Panel(string heading,string body,string button,UnityEngine.Events.UnityAction action){var p=new GameObject("Chapter Overlay");p.transform.SetParent(ui.transform,false);var r=p.AddComponent<RectTransform>();r.anchorMin=r.anchorMax=new Vector2(.5f,.5f);r.pivot=new Vector2(.5f,.5f);r.sizeDelta=new Vector2(900,450);var bg=p.AddComponent<Image>();bg.color=new(.006f,.01f,.018f,.98f);var k=Child(p,"Kicker",new(0,-48),new(820,30),12,TextAnchor.MiddleCenter);k.text="MARA VALE · COURIER 17";k.color=ember;var h=Child(p,"Heading",new(0,-102),new(820,65),46,TextAnchor.MiddleCenter);h.text=heading;var b=Child(p,"Body",new(0,-190),new(760,90),18,TextAnchor.MiddleCenter);b.text=body;b.color=new(.7f,.74f,.8f);var go=new GameObject("Button");go.transform.SetParent(p.transform,false);var br=go.AddComponent<RectTransform>();br.anchorMin=br.anchorMax=new Vector2(.5f,0);br.pivot=new Vector2(.5f,0);br.anchoredPosition=new Vector2(0,45);br.sizeDelta=new Vector2(340,68);var bi=go.AddComponent<Image>();bi.color=ember;var bu=go.AddComponent<Button>();bu.onClick.AddListener(action);var lab=Child(go,"Label",Vector2.zero,new Vector2(340,68),17,TextAnchor.MiddleCenter);lab.text=button;lab.color=Color.black;return p;}
        void StartChapter(){if(panel)Destroy(panel);running=true;dead=won=bossActive=false;hp=100;kills=score=wave=0;t=distance=0;spawn=.35f;fire=.05f;bossHp=600;velocity=Vector2.zero;mara.position=new Vector3(-3,-1.3f,0);goal.text=Goal();}
        string Goal()=>chapter switch{Chapter.Delivery=>"REACH EXTRACTION · A/D OR ARROWS · SPACE/W JUMP · ENTER FIRE",Chapter.Complex=>"SURVIVE 6 WAVES · TAKEDOWNS POWER YOUR LOADOUT",Chapter.Getaway=>"LOSE THE HEAT · REACH 2,000m · PURSUIT INCOMING",Chapter.Vault=>"28 TAKEDOWNS · THEN DEFEAT THE WARDEN",_=>"DEFEAT THE ARCHITECT · COMPLETE MARA'S RUN"};
        void Update(){if(!running)return;float dt=Mathf.Min(Time.deltaTime,.033f);t+=dt;distance+=dt*5.4f;Input(dt);Sim(dt);cam.transform.position=Vector3.Lerp(cam.transform.position,new Vector3(mara.position.x+2.2f,.1f,-20),1-Mathf.Exp(-7*dt));hud.text=$"HP {hp:000}   SCORE {score:000000}   TAKEDOWNS {kills:00}   WAVE {wave:00}   DIST {distance:0000}m";if(bossActive)goal.text=$"BOSS // {Mathf.Max(0,bossHp):000} HP";if(dead){running=false;panel=Panel("MARA IS DOWN","The shard is still in Mara's hand. One more run.","RETRY",StartChapter);}else if(won){running=false;if((int)chapter<4){chapter++;ShowChapter();}else panel=Panel("RUN COMPLETE","Five chapters. One courier. The story is only beginning.","PLAY AGAIN",()=>{chapter=Chapter.Delivery;ShowChapter();});}}
        void Input(float dt){var k=Keyboard.current;if(k==null)return;float x=(k.dKey.isPressed||k.rightArrowKey.isPressed?1:0)-(k.aKey.isPressed||k.leftArrowKey.isPressed?1:0);velocity.x=Mathf.MoveTowards(velocity.x,x*7,30*dt);if((k.spaceKey.wasPressedThisFrame||k.wKey.wasPressedThisFrame||k.upArrowKey.wasPressedThisFrame)&&mara.position.y<=-1.28f)velocity.y=9.5f;velocity.y-=23*dt;mara.position+=(Vector3)(velocity*dt);if(mara.position.y<-1.28f){mara.position=new Vector3(mara.position.x,-1.28f,0);velocity.y=0;}mara.position=new Vector3(Mathf.Clamp(mara.position.x,-7.3f,7.3f),mara.position.y,0);if(k.enterKey.wasPressedThisFrame||k.eKey.wasPressedThisFrame)Fire();}
        void Sim(float dt){fire-=dt;spawn-=dt;if(fire<=0){Fire();fire=chapter==Chapter.Complex?.16f:.23f;}if(spawn<=0){Spawn();spawn=Mathf.Max(.35f,1.12f-Mathf.Min(.55f,t*.012f));}MoveShots(dt);MoveEnemies(dt);if(chapter==Chapter.Delivery&&distance>48)won=true;if(chapter==Chapter.Getaway&&distance>370)won=true;if(chapter==Chapter.Complex&&wave>=6)won=true;if(chapter==Chapter.Vault&&kills>=28&&!bossActive){bossActive=true;SpawnBoss();}if(chapter==Chapter.Final&&t>12&&!bossActive){bossActive=true;SpawnBoss();}if(bossActive&&bossHp<=0)won=true;if(chapter==Chapter.Complex)wave=Mathf.Clamp(kills/6,0,6);}
        void Fire(){if(!running)return;var g=new GameObject("Projectile");g.transform.position=mara.position+new Vector3(.95f,.05f,0);g.transform.localScale=new Vector3(1.1f,.08f,1);var r=g.AddComponent<SpriteRenderer>();r.sprite=pixel;r.sortingOrder=50;r.color=chapter==Chapter.Getaway?gold:ember;shots.Add(new Shot{go=g,speed=chapter==Chapter.Getaway?20:18,damage=25});for(int i=0;i<3;i++){var fx=Box("MuzzleFlash",mara.position+new Vector2(.9f+Random.value*.25f,Random.Range(-.1f,.1f)),new(.2f,.06f),gold,51);Destroy(fx,.1f);}}
        void MoveShots(float dt){for(int i=shots.Count-1;i>=0;i--){var s=shots[i];if(!s.go){shots.RemoveAt(i);continue;}s.go.transform.position+=Vector3.right*s.speed*dt;bool hit=s.go.transform.position.x>15;for(int e=enemies.Count-1;e>=0&&!hit;e--){var a=enemies[e];if(!a.go)continue;if(Vector2.Distance(s.go.transform.position,a.go.transform.position)<(a.boss?1.6f:1.05f)){a.hp-=s.damage;hit=true;for(int z=0;z<4;z++){var fx=Box("HitFX",a.go.transform.position+Random.insideUnitCircle*.2f,new(.1f,.1f),gold,52);Destroy(fx,.12f);}if(a.hp<=0){if(a.boss)bossHp=0;else{kills++;score+=100;Destroy(a.go);enemies.RemoveAt(e);}}}}if(hit){Destroy(s.go);shots.RemoveAt(i);}}}
        void MoveEnemies(float dt){for(int i=enemies.Count-1;i>=0;i--){var a=enemies[i];if(!a.go){enemies.RemoveAt(i);continue;}a.go.transform.position+=Vector3.left*(a.boss?.75f:chapter==Chapter.Getaway?5.4f:1.9f)*dt;if(Vector2.Distance(a.go.transform.position,mara.position)<(a.boss?1.45f:.85f)){hp-=a.boss?20:9;Destroy(a.go);enemies.RemoveAt(i);if(hp<=0){dead=true;return;}}else if(a.go.transform.position.x<-11){Destroy(a.go);enemies.RemoveAt(i);}}}
        void Spawn(){if(chapter==Chapter.Getaway){var c=Box("Enemy Pursuit Car",new(9,Random.Range(-1.7f,.8f)),new(2.1f,.72f),new(.62f,.05f,.08f),35);Box("Headlight",c.transform.position+new Vector3(.82f,.08f,0),new(.13f,.15f),gold,36);enemies.Add(new Actor{go=c,hp=60});return;}Color c2=chapter==Chapter.Vault?new(.56f,.16f,.78f):chapter==Chapter.Final?new(.72f,.07f,.12f):new(.12f,.38f,.48f);var g=Box("Enemy",new(9,Random.Range(-1.7f,1.25f)),chapter==Chapter.Vault?new(1.15f,1.8f):new(.85f,1f),c2,35);enemies.Add(new Actor{go=g,hp=chapter==Chapter.Final?70:45});}
        void SpawnBoss(){var g=Box("BOSS",new(6.2f,.1f),new(2.8f,3f),chapter==Chapter.Final?new(.72f,.06f,.1f):new(.44f,.15f,.68f),38);enemies.Add(new Actor{go=g,hp=600,boss=true});}
    }
}
