import Link from "next/link";
const chapters=[
 {n:"01",title:"Rooftop Runner",desc:"Mara Vale. One delivery. One lockdown. Run the shard across the rooftops.",href:"/games/last-stand",state:"PLAY"},
 {n:"02",title:"One More Room",desc:"The shard leads underground. Fight through the relay complex.",href:"/games/one-more-room",state:"ENTER"},
 {n:"03",title:"The Getaway",desc:"District 9 is closing in. Drive hard, manage the heat and reach the relay.",href:"/games/the-getaway",state:"DRIVE"},
 {n:"04",title:"Dungeon 7",desc:"Five security waves stand between Mara and the source beneath the city.",href:"/games/dungeon-7",state:"DESCEND"},
 {n:"05",title:"The Final Run",desc:"Meridian Tower. The Director. The truth behind Courier 17.",href:"/games/the-final-run",state:"FINALE"},
];
export default function Games(){return <main className="min-h-screen px-6 py-8 lg:px-10"><header className="mx-auto flex max-w-7xl justify-between"><Link href="/" className="text-sm font-black uppercase tracking-[.18em]">Small Game Lab.</Link><span className="text-xs font-bold uppercase tracking-[.2em] text-zinc-600">The Long Run · Campaign</span></header><section className="mx-auto max-w-7xl py-20"><p className="text-xs font-bold uppercase tracking-[.3em] text-orange-500">The Long Run</p><h1 className="mt-5 max-w-5xl text-6xl font-black tracking-[-.05em] sm:text-8xl">ONE STORY.<br/>FIVE ARCADE GAMES.</h1><p className="mt-8 max-w-2xl text-sm leading-7 text-zinc-500">Play Mara Vale's complete run from rooftop courier to Meridian Tower. Each chapter changes the mechanic, but every chapter moves the same story forward.</p><div className="mt-16 border-t border-zinc-800">{chapters.map((c,i)=><article key={c.n} className="group flex flex-col gap-8 border-b border-zinc-800 py-8 md:flex-row md:items-center md:justify-between"><div className="flex gap-6"><span className="pt-2 text-xs text-zinc-600">{c.n}</span><div><h2 className="text-3xl font-black uppercase tracking-tight sm:text-5xl">{c.title}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-500">{c.desc}</p></div></div><Link href={c.href} className={`w-fit shrink-0 px-6 py-3 text-sm font-black uppercase ${i===0?"bg-orange-500 text-black":"border border-zinc-700 text-zinc-200 hover:border-orange-500"}`}>{c.state} →</Link></article>)}</div></section></main>}
